const characters = {
	jx_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_rende", "jijiang"],
		isZhugong: true,
	},
	jx_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_wusheng", "yijue"],
	},
	jx_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_paoxiao", "tishen"],
	},
	jx_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jx_guanxing", "kongcheng"],
	},
	jx_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longdan", "yajiao"],
	},
	jx_machao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "jx_tieji"],
	},
	jx_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["jx_jizhi", "jx_qicai"],
	},
	jx_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jx_zhiheng", "jx_jiuyuan"],
		isZhugong: true,
	},
	jx_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qixi", "fenwei"],
	},
	jx_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["keji", "qinxue"],
	},
	jx_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jx_kurou", "zhaxiang"],
	},
	jx_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["jx_yingzi", "jx_fanjian"],
	},
	jx_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jx_guose", "liuli"],
	},
	jx_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["jx_qianxun", "jx_lianying"],
	},
	jx_sunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jx_jieyin", "xiaoji"],
	},
	jx_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_jianxiong", "hujia"],
		isZhugong: true,
	},
	jx_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jx_fankui", "jx_guicai"],
	},
	jx_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_ganglie", "qingjian"],
	},
	jx_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_tuxi"],
	},
	jx_xuchu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_luoyi"],
	},
	jx_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "jx_yiji"],
	},
	jx_zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["jx_qingguo", "luoshen"],
	},
	jx_huatuo: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jijiu", "chuli"],
	},
	jx_lvbu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["wushuang", "liyu"],
	},
	jx_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["lijian", "jx_biyue"],
	},
	jx_huaxiong: {
		sex: "male",
		group: "qun",
		hp: 6,
		skills: ["jx_yaowu"],
	},
	jx_gongsunzan: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yicong", "qiaomeng"],
	},
	std_yiji: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jijie", "jiyuan"],
	},
	caozhang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jiangchi"],
	},
};

export default characters;
