const characters = {
  caoang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["kangkai"],
  },
  xuelingyun: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["siqi", "qiaozhi"],
  },
  xiahouxuan: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["huanfu", "qingyi", "zeyue"],
  },
  yanrou: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["choutao", "xiangshu"],
  },
  qinghegongzhu: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["zengou", "zhangji"],
  },
  caofang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["zhimin", "jujian"],
    isZhugong: true,
  },
  duyu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jianguo", "qingshi"],
    groupBorder: "jin",
  },
  huanfan: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["jianzheng", "fumou"],
  },
  zhenghun: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["qiangzhi", "pitian"],
  },
  zhaoyan: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["funing", "bingji"],
  },
  wenqin: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["guangao", "huiqi"],
  },
  jx_zhonghui: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jx_quanji", "zili"],
  },
  yanghuiyu: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["hongyi", "quanfeng"],
    groupBorder: "jin",
  },
  xizhicai: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "xianfu", "chouce"],
  },
  jx_zhangchunhua: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["jueqing", "shangshi", "jianmie"],
  },
  wangyuanji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["qianchong", "shangjian"],
    groupBorder: "jin",
  },
  caoying: {
    sex: "female",
    group: "wei",
    hp: 4,
    skills: ["lingren", "fujian"],
  },
  caochun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["shanjia"],
  },
  zhaoang: {
    sex: "male",
    group: "wei",
    hp: 3,
    maxHp: 4,
    skills: ["zhongjie", "sushou"],
  },
  jx_manchong: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["jx_junxing", "yuce"],
  },
  bianyue: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["bizu", "jwuxie"],
  },
  chengjichengcui: {
    sex: "male",
    group: "wei",
    hp: 6,
    skills: ["tousui", "chuming"],
    groupBorder: "jin",
  },
  qianzhao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["weifu", "kuansai"],
  },
  huban: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["huiyun"],
  },
  bianxi: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["dunxi"],
  },
  maliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["yingyuan", "zishu"],
  },
  jiangwan: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["ziruo", "xvfa"],
  },
  feiyi: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["yanru", "hezhong"],
  },
  pengyang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["xiaofan", "tuishi", "cunmu"],
  },
  mengda: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["goude"],
  },
  zhangyi: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["zhiyi"],
  },
  chenshi: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["qingbei"],
  },
  yangyi: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["dingcuo", "juanxia"],
  },
  huangwudie: {
    sex: "female",
    group: "shu",
    hp: 4,
    skills: ["shuangrui", "fuxie"],
  },
  shamoke: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["jili"],
  },
  wolongfengchu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["youlong", "luanfeng"],
  },
}

export default characters
