const characters = {
	jx_zhoutai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jx_buqu", "fenji"],
	},
	jx_yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jx_guhuo"],
	},
	jx_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jx_leiji", "guidao", "huangtian"],
		isZhugong: true,
	},
	jx_huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_liegong"],
	},
	jx_weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_kuanggu", "qimou"],
	},
	jx_xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_shensu"],
	},
	jx_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_jushou", "jiewei"],
	},
	jx_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jx_tianxiang", "hongyan"],
	},
	jx_wolongzhuge: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["bazhen", "jx_huoji", "jx_kanpo"],
	},
	jx_dianwei: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_qiangxi"],
	},
	jx_xunyu: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["quhu", "jx_jieming"],
	},
	jx_pangde: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["mashu", "jianchu"],
	},
	jx_pangtong: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["jx_lianhuan", "jx_niepan"],
	},
	jx_yanliangwenchou: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jx_shuangxiong"],
	},
	jx_yuanshao: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["jx_luanji", "xueyi"],
		isZhugong: true,
	},
	jx_taishici: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jx_tianyi", "dangmo"],
	},
	jx_xuhuang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_duanliang", "jiezi"],
	},
	jx_menghuo: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["huoshou", "jx_zaiqi"],
	},
	jx_zhurong: {
		sex: "female",
		group: "shu",
		hp: 4,
		skills: ["juxiang", "jx_lieren"],
	},
	jx_caopi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jx_xingshang", "jx_fangzhu", "songwei"],
		isZhugong: true,
	},
	jx_sunjian: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["yinghun", "polu"],
	},
	jx_dongzhuo: {
		sex: "male",
		group: "qun",
		hp: 8,
		skills: ["jx_jiuchi", "roulin", "benghuai", "baonue"],
		isZhugong: true,
	},
	jx_lusu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["jx_haoshi", "jx_dimeng"],
	},
	jx_jiaxu: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jx_wansha", "jx_weimu", "luanwu"],
	},
	jx_dengai: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_tuntian", "zaoxian"],
	},
	jx_jiangwei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_tiaoxin", "jx_zhiji"],
	},
	jx_caiwenji: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["jx_beige", "duanchang"],
	},
	jx_zuoci: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jx_huashen", "jx_xinsheng"],
	},
	jx_sunce: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jiang", "jx_hunzi", "zhiba"],
		isZhugong: true,
	},
	jx_zhangzhaozhanghong: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["jx_zhijian", "guzheng"],
	},
	jx_liushan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xiangle", "jx_fangquan", "ruoyu"],
		isZhugong: true,
	},
	jx_zhanghe: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_qiaobian"],
	},
	wangji: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["qizhi", "jinqu"],
	},
	yanyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["juzhan"],
	},
	wangping: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["feijun", "binglve"],
	},
	luji: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["huaiju", "yili", "zhenglun"],
		clans: ["吴郡陆氏"],
	},
	sunliang: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["kuizhu", "zhizheng", "lijun"],
		isZhugong: true,
	},
	kuaiyuekuailiang: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["jianxiang", "shenshi"],
		names: "蒯|良-蒯|越",
	},
	xuyou: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["chenglve", "shicai", "cunmu"],
	},
	luzhi: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["mingren", "zhenliang"],
	},
	guanqiujian: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhengrong", "hongju"],
	},
	chendao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["wanglie"],
	},
	zhugezhan: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["zuilun", "fuyin"],
	},
	zhoufei: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["liangyin", "kongsheng"],
	},
	lukang: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qianjie", "jueyan", "poshi"],
		clans: ["吴郡陆氏"],
	},
	zhangxiu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["xiongluan", "congjian"],
		isZhugong: true,
	},
	haozhao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["zhengu"],
	},
	yuanshu: {
		sex: "male",
		group: "qun",
		hp: 4,
		skills: ["yongsi", "weidi"],
		isZhugong: true,
	},
	le_guanyu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["wushen", "wuhun"],
		groupInGuozhan: "shu",
	},
	le_lvmeng: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["shelie", "gongxin"],
		groupInGuozhan: "wu",
	},
	le_zhouyu: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["qinyin", "yeyan"],
		groupInGuozhan: "wu",
	},
	le_zhugeliang: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["qixing", "kuangfeng", "dawu"],
		groupInGuozhan: "shu",
	},
	le_caocao: {
		sex: "male",
		group: "shen",
		hp: 3,
		skills: ["guixin", "feiying"],
		groupInGuozhan: "wei",
	},
	le_lvbu: {
		sex: "male",
		group: "shen",
		hp: 5,
		skills: ["kuangbao", "wumou", "wuqian", "shenfen"],
		groupInGuozhan: "qun",
	},
	jle_zhaoyun: {
		sex: "male",
		group: "shen",
		hp: 2,
		skills: ["juejing", "longhun"],
		groupInGuozhan: "shu",
		img: "image/character/le_zhaoyun.jpg",
		dieAudios: ["le_zhaoyun"],
	},
	jle_simayi: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["renjie", "sbaiyin", "lianpo"],
		groupInGuozhan: "wei",
		img: "image/character/le_simayi.jpg",
		dieAudios: ["le_simayi"],
	},
	le_liubei: {
		sex: "male",
		group: "shen",
		hp: 6,
		skills: ["longnu", "jieying"],
		groupInGuozhan: "shu",
	},
	le_luxun: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["junlve", "cuike", "zhanhuo"],
		groupInGuozhan: "wu",
	},
	le_zhangliao: {
		sex: "male",
		group: "shen",
		hp: 4,
		skills: ["duorui", "zhiti"],
		groupInGuozhan: "wei",
	},
	le_ganning: {
		sex: "male",
		group: "shen",
		hp: 3,
		maxHp: 6,
		skills: ["poxi", "ljieying"],
		groupInGuozhan: "wu",
	},
};

export default characters;
