const characters = {
	jx_zhoutai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["jx_buqu", "fenji"],
	},
	jx_yuji: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jx_guhuo"],
	},
	jx_zhangjiao: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jx_leiji", "guidao", "huangtian"],
		isZhugong: true,
	},
	jx_huangzhong: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_liegong"],
	},
	jx_weiyan: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["jx_kuanggu", "qimou"],
	},
	jx_xiahouyuan: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_shensu"],
	},
	jx_caoren: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["jx_jushou", "jiewei"],
	},
	jx_xiaoqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["jx_tianxiang", "hongyan"],
	},
	// jx_xuhuang: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["duanliang", "jiezi"],
	// },
	// jx_pangde: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["mashu", "jianchu"],
	// },

	// jx_wolongzhuge: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["bazhen", "rehuoji", "rekanpo"],
	// 	names: "诸葛|亮",
	// },
	// jx_pangtong: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["xinlianhuan", "niepan"],
	// },
	// jx_xunyu: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["quhu", "rejieming"],
	// 	clans: ["颍川荀氏"],
	// },
	// jx_dianwei: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["qiangxix"],
	// },
	// jx_taishici: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["tianyi"],
	// 	names: "太史|慈",
	// },
	// jx_yanwen: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["shuangxiong"],
	// 	names: "颜|良-文|丑",
	// },
	// jx_yuanshao: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["luanji", "xueyi"],
	// 	isZhugong: true,
	// 	dieAudios: ["yuanshao"],
	// },

	// jx_menghuo: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["huoshou", "zaiqixx", "twqiushou"],
	// 	isZhugong: true,
	// 	doubleGroup: ["shu", "qun"],
	// },
	// jx_zhurong: {
	// 	sex: "female",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["juxiang", "lieren"],
	// 	doubleGroup: ["shu", "qun"],
	// 	names: "null|null",
	// },
	// jx_caopi: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["xingshang", "fangzhu", "songwei"],
	// 	isZhugong: true,
	// },
	// jx_lusu: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["haoshi", "dimeng"],
	// },
	// jx_sunjian: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["gzyinghun"],
	// },
	// jx_dongzhuo: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 8,
	// 	skills: ["jiuchi", "roulin", "benghuai", "baonue"],
	// 	isZhugong: true,
	// },
	// jx_jiaxu: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["luanwu", "wansha", "weimu"],
	// },

	// jx_jiangwei: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["tiaoxin", "zhiji"],
	// },
	// jx_liushan: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["xiangle", "fangquan", "ruoyu"],
	// 	isZhugong: true,
	// },
	// jx_zhanghe: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["qiaobian"],
	// },
	// jx_dengai: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["tuntian", "zaoxian"],
	// },
	// jx_sunce: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["jiang", "hunzi", "zhiba"],
	// 	isZhugong: true,
	// },
	// jx_zhangzhang: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["zhijian", "guzheng"],
	// 	names: "张|昭-张|纮",
	// },
	// jx_caiwenji: {
	// 	sex: "female",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["beige", "duanchang"],
	// },
	// jx_zuoci: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["huashen", "xinsheng"],
	// },
	// wangji: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["qizhi", "jinqu"],
	// },
	// yanyan: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["nzry_juzhan"],
	// },
	// wangping: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["nzry_feijun", "nzry_binglve"],
	// },
	// luji: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["nzry_huaiju", "nzry_yili", "nzry_zhenglun"],
	// 	clans: ["吴郡陆氏"],
	// },
	// sunliang: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["nzry_kuizhu", "nzry_zhizheng", "nzry_lijun"],
	// 	isZhugong: true,
	// },
	// xuyou: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["nzry_chenglve", "nzry_shicai", "nzry_cunmu"],
	// },
	// yl_luzhi: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 3,
	// 	skills: ["nzry_mingren", "nzry_zhenliang"],
	// },
	// kuailiangkuaiyue: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 3,
	// 	skills: ["nzry_jianxiang", "nzry_shenshi"],
	// 	names: "蒯|良-蒯|越",
	// },
	// guanqiujian: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["zhengrong", "hongju"],
	// 	names: "毌丘|俭",
	// },
	// haozhao: {
	// 	sex: "male",
	// 	group: "wei",
	// 	hp: 4,
	// 	skills: ["drlt_zhengu"],
	// },
	// zhugezhan: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 3,
	// 	skills: ["xinfu_zuilun", "xinfu_fuyin"],
	// 	names: "诸葛|瞻",
	// },
	// lukang: {
	// 	sex: "male",
	// 	group: "wu",
	// 	hp: 4,
	// 	skills: ["drlt_qianjie", "drlt_jueyan", "drlt_poshi"],
	// 	clans: ["吴郡陆氏"],
	// },
	// yl_yuanshu: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["drlt_yongsi", "drlt_weidi"],
	// 	isZhugong: true,
	// },
	// zhangxiu: {
	// 	sex: "male",
	// 	group: "qun",
	// 	hp: 4,
	// 	skills: ["drlt_xiongluan", "drlt_congjian", "twjuxiang"],
	// 	isZhugong: true,
	// },
	// chendao: {
	// 	sex: "male",
	// 	group: "shu",
	// 	hp: 4,
	// 	skills: ["dcwanglie"],
	// },
	// zhoufei: {
	// 	sex: "female",
	// 	group: "wu",
	// 	hp: 3,
	// 	skills: ["olliangyin", "olkongsheng"],
	// 	names: "周|null",
	// },
};

export default characters;
