const characterSort = {
  jieshenhua_feng: [
    "jx_zhoutai",
    "jx_yuji",
    "jx_zhangjiao",
    "jx_huangzhong",
    "jx_weiyan",
    "jx_xiahouyuan",
    "jx_caoren",
    "jx_xiaoqiao",
    "le_guanyu",
    "le_lvmeng",
  ],
  jieshenhua_huo: [
    "jx_wolongzhuge",
    "jx_dianwei",
    "jx_xunyu",
    "jx_pangde",
    "jx_pangtong",
    "jx_yanliangwenchou",
    "jx_yuanshao",
    "jx_taishici",
    "le_zhouyu",
    "le_zhugeliang",
  ],
  jieshenhua_lin: [
    "jx_xuhuang",
    "jx_menghuo",
    "jx_zhurong",
    "jx_caopi",
    "jx_sunjian",
    "jx_dongzhuo",
    "jx_lusu",
    "jx_jiaxu",
    "le_caocao",
    "le_lvbu",
  ],
  jieshenhua_shan: [
    "jx_dengai",
    "jx_jiangwei",
    "jx_caiwenji",
    "jx_zuoci",
    "jx_sunce",
    "jx_zhangzhaozhanghong",
    "jx_liushan",
    "jx_zhanghe",
    "jle_zhaoyun",
    "jle_simayi",
  ],
  shenhua_yin: [
    "wangji",
    "yanyan",
    "wangping",
    "luji",
    "sunliang",
    "kuaiyuekuailiang",
    "xuyou",
    "luzhi",
    "le_liubei",
    "le_luxun",
  ],
  shenhua_lei: [
    "guanqiujian",
    "chendao",
    "zhugezhan",
    "zhoufei",
    "lukang",
    "zhangxiu",
    "haozhao",
    "yuanshu",
    "le_zhangliao",
    "le_ganning",
  ],
}

const characterSortTranslate = {
  jieshenhua_feng: "界神话再临·风",
  jieshenhua_huo: "界神话再临·火",
  jieshenhua_lin: "界神话再临·林",
  jieshenhua_shan: "界神话再临·山",
  shenhua_yin: "神话再临·阴",
  shenhua_lei: "神话再临·雷",
}

export { characterSort, characterSortTranslate }
