window.wtk_character_rank = {
  s: [],
  ap: [],
  a: [],
  am: [
    "old_xiahoudun",
    "old_lvbu",

    "re_lvbu",
    "ol_lvbu",
  ],
  bp: [
    "re_huanggai",
    "ol_huanggai",

    "re_guojia",
    "ol_guojia",
  ],
  b: [
    "wangji",
    "re_liubei",
    "ol_liubei",
    "re_guanyu",
    "ol_guanyu",
    "old_zhaoyun",
    "re_zhaoyun",
    "ol_zhaoyun",
    "re_sunquan",
    "ol_sunquan",
    "re_lvmeng",
    "ol_lvmeng",
    "re_daqiao",
    "ol_daqiao",
    "re_sunshangxiang",
    "ol_sunshangxiang",
    "re_huatuo",
    "ol_huatuo",
    "re_diaochan",
    "ol_diaochan",
    "ol_huaxiong",
  ],
  bm: [
    "old_zhangliao",

    "re_xiahoudun",
    "ol_xiahoudun",
    "re_zhangliao",
    "ol_zhangliao",

    "old_xuzhu",
    "re_xuzhu",
    "ol_xuzhu",
    "ol_zhenji",
    "old_guanyu",
    "re_zhangfei",
    "ol_zhangfei",
    "re_zhugeliang",
    "ol_zhugeliang",
    "re_huangyueying",
    "ol_huangyueying",
    "re_zhouyu",
    "ol_zhouyu",
    "re_luxun",
    "ol_luxun",
    "yanyan",
  ],
  c: [
    "zhangliao",
    "guojia",
    "huangyueying",
    "sunquan",
    "huanggai",
    "zhouyu",
    "daqiao",
    "sunshangxiang",
    "huatuo",
    "old_diaochan",

    "diaochan",

    "re_caocao",
    "ol_caocao",
    "old_guojia",
    "re_machao",
    "ol_machao",
    "re_ganning",
    "ol_ganning",
  ],
  d: [
    "caocao",
    "simayi",
    "xiahoudun",
    "xuzhu",
    "zhenji",
    "liubei",
    "guanyu",
    "zhangfei",
    "zhugeliang",
    "zhaoyun",
    "machao",
    "ganning",
    "lvmeng",
    "luxun",
    "lvbu",

    "old_liubei",
    "old_huangyueying",
    "huaxiong",
    "old_yuanshu",

    "old_caocao",
    "re_simayi",
    "ol_simayi",
    "re_zhenji",
    "old_liubei",
    "old_zhangfei",
    "re_huaxiong",
  ],
  rarity: {
    legend: ["re_machao", "ol_machao"],
    epic: ["old_xiahoudun"],
    rare: [
      "zhangliao",
      "guojia",

      "re_xiahoudun",
      "ol_xiahoudun",
      "old_guojia",
      "re_guojia",
      "ol_guojia",
      "ol_zhenji",
      "re_liubei",
      "ol_liubei",
      "old_guanyu",
      "re_guanyu",
      "ol_guanyu",
      "re_zhangfei",
      "ol_zhangfei",
      "re_zhugeliang",
      "ol_zhugeliang",
      "old_zhaoyun",
      "re_zhaoyun",
      "ol_zhaoyun",
      "re_huangyueying",
      "ol_huangyueying",
      "re_sunquan",
      "ol_sunquan",
      "re_lvmeng",
      "ol_lvmeng",
      "re_huanggai",
      "ol_huanggai",
      "re_zhouyu",
      "ol_zhouyu",
      "re_daqiao",
      "ol_daqiao",
      "re_sunshangxiang",
      "ol_sunshangxiang",
      "re_huatuo",
      "ol_huatuo",
      "old_lvbu",
      "re_lvbu",
      "ol_lvbu",
      "re_diaochan",
      "ol_diaochan",
      "ol_huaxiong",
      "yanyan",
    ],
    junk: [
      "caocao",
      "simayi",
      "xiahoudun",
      "xuzhu",
      "zhenji",
      "liubei",
      "guanyu",
      "zhangfei",
      "zhugeliang",
      "zhaoyun",
      "machao",
      "huangyueying",
      "sunquan",
      "ganning",
      "lvmeng",
      "huanggai",
      "zhouyu",
      "daqiao",
      "luxun",
      "sunshangxiang",
      "huatuo",
      "lvbu",
      "old_diaochan",

      "old_liubei",
      "old_huangyueying",
      "diaochan",
      "huaxiong",
      "old_yuanshu",

      "old_caocao",
      "re_simayi",
      "ol_simayi",
      "old_zhangliao",

      "re_caocao",
      "ol_caocao",
      "re_zhangliao",
      "ol_zhangliao",
      "old_xuzhu",
      "re_xuzhu",
      "ol_xuzhu",

      "re_zhenji",
      "old_liubei",
      "old_zhangfei",
      "re_ganning",
      "ol_ganning",
      "re_luxun",
      "ol_luxun",
      "re_huaxiong",
    ],
  },
}
