window.noname_character_rank = {
	s: [],
	ap: [],
	a: [],
	am: [],
	bp: [],
	b: [],
	bm: [],
	c: ["huangyueying", "ganfuren", "sunquan", "huanggai", "zhouyu", "daqiao", "sunshangxiang", "zhangliao", "guojia", "huatuo", "diaochan"],
	d: [
		"liubei",
		"guanyu",
		"zhangfei",
		"zhugeliang",
		"zhaoyun",
		"machao",
		"ganning",
		"lvmeng",
		"luxun",
		"caocao",
		"simayi",
		"xiahoudun",
		"xuzhu",
		"zhenji",
		"yuejin",
		"lvbu",
		"panfeng",
		"huaxiong",
		"gongsunzan",
	],
	rarity: {
		legend: [],
		epic: [],
		rare: ["ganfuren", "zhangliao", "guojia"],
		junk: [
			"liubei",
			"guanyu",
			"zhangfei",
			"zhugeliang",
			"zhaoyun",
			"machao",
			"huangyueying",
			"sunquan",
			"ganning",
			"lvmeng",
			"huanggai",
			"zhouyu",
			"daqiao",
			"luxun",
			"sunshangxiang",
			"caocao",
			"simayi",
			"xiahoudun",
			"xuzhu",
			"zhenji",
			"yuejin",
			"huatuo",
			"lvbu",
			"diaochan",
			"panfeng",
			"huaxiong",
			"gongsunzan",
		],
	},
};
