const characters = {
  re_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejianxiong", "hujia"],
    isZhugong: true,
  },
  re_simayi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["refankui", "reguicai"],
    names: "司马|懿",
  },
  re_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reganglie", "qingjian"],
    names: "夏侯|惇",
  },
  re_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["retuxi"],
  },
  re_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reluoyi"],
  },
  re_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "reyiji"],
  },
  re_zhenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["luoshen", "reqingguo"],
  },
  lidian: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["xunxun", "wangxi"],
  },
  re_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rerende", "jijiang"],
    isZhugong: true,
  },
  re_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rewusheng", "yijue"],
  },
  re_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["repaoxiao", "tishen"],
  },
  re_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["reguanxing", "kongcheng"],
    names: "诸葛|亮",
  },
  re_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["longdan", "yajiao"],
  },
  re_machao: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "retieji"],
  },
  re_huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["rejizhi", "reqicai"],
  },
  xushu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["zhuhai", "qianxin"],
  },
  re_sunquan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rezhiheng", "rejiuyuan"],
    isZhugong: true,
  },
  re_ganning: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["qixi", "fenwei"],
  },
  re_lvmeng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["keji", "qinxue"],
  },
  re_huanggai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["kurou"],
  },
  re_zhouyu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["yingzi", "fanjian"],
  },
  re_daqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["guose", "liuli"],
    names: "桥|null",
  },
  re_luxun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["qianxun", "lianying"],
    clans: ["吴郡陆氏"],
  },
  re_sunshangxiang: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["jieyin", "xiaoji"],
  },
  re_huatuo: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jijiu", "qingnang"],
  },
  re_lvbu: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["wushuang"],
  },
  re_diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["lijian", "biyue"],
    names: "null|null",
  },
  re_huaxiong: {
    sex: "male",
    group: "qun",
    hp: 6,
    skills: ["yaowu"],
  },
}

export default characters
