const characters = {
  re_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejianxiong", "hujia"],
    isZhugong: true,
  },
  re_simayi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["refankui", "reguicai"],
    names: "司马|懿",
  },
  re_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reganglie", "qingjian"],
    names: "夏侯|惇",
  },
  re_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["retuxi"],
  },
  re_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reluoyi"],
  },
  re_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "reyiji"],
  },
  re_zhenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["luoshen", "reqingguo"],
  },
  re_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rerende", "jijiang"],
    isZhugong: true,
  },
  re_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rewusheng", "yijue"],
  },
  re_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["repaoxiao", "tishen"],
  },
  re_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["reguanxing", "kongcheng"],
    names: "诸葛|亮",
  },
  re_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["longdan", "yajiao"],
  },
  re_machao: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "retieji"],
  },
  re_huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["rejizhi", "reqicai"],
  },
  re_sunquan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rezhiheng", "rejiuyuan"],
    isZhugong: true,
  },
  re_ganning: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["qixi", "fenwei"],
  },
  re_lvmeng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["keji", "qinxue"],
  },
  re_huanggai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rekurou", "zhaxiang"],
  },
  re_zhouyu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reyingzi", "refanjian"],
  },
  re_daqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["reguose", "liuli"],
    names: "桥|null",
  },
  re_luxun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reqianxun", "relianying"],
    clans: ["吴郡陆氏"],
  },
  re_sunshangxiang: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["rejieyin", "rexiaoji"],
  },
  re_huatuo: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jijiu", "chuli"],
  },
  re_lvbu: {
    sex: "male",
    group: "qun",
    hp: 5,
    skills: ["wushuang", "liyu"],
  },
  re_diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["lijian", "rebiyue"],
    names: "null|null",
  },
  re_huaxiong: {
    sex: "male",
    group: "qun",
    hp: 6,
    skills: ["reyaowu"],
  },
  re_gongsunzan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["qiaomeng", "yicong"],
  },
  caozhang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jiangchi"],
  },
  re_yiji: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["jijie", "jiyuan"],
  },
}

export default characters
