export default {
  re_caocao: "魏武帝",
  re_simayi: "狼顾之鬼",
  re_xiahoudun: "独眼的罗刹",
  re_zhangliao: "前将军",
  re_xuzhu: "虎痴",
  re_guojia: "早终的先知",
  re_zhenji: "薄幸的美人",
  lidian: "深明大义",

  re_liubei: "乱世的枭雄",
  re_guanyu: "美髯公",
  re_zhangfei: "万夫不当",
  re_zhugeliang: "迟暮的丞相",
  re_zhaoyun: "虎威将军",
  re_machao: "一骑当千",
  re_huangyueying: "归隐的杰女",

  re_sunquan: "年轻的贤君",
  re_ganning: "锦帆游侠",
  re_lvmeng: "白衣渡江",
  re_huanggai: "轻身为国",
  re_zhouyu: "大都督",
  re_daqiao: "矜持之花",
  re_luxun: "儒生雄才",
  re_sunshangxiang: "弓腰姬",

  re_huatuo: "神医",
  re_lvbu: "武的化身",
  re_diaochan: "绝世的舞姬",
}
