const characters = {
  re_huangzhong: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["reliegong"],
  },
  re_weiyan: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rekuanggu", "qimou"],
  },
  re_xiahouyuan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reshensu"],
    names: "夏侯|渊",
  },
  re_caoren: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejushou", "jiewei"],
  },
  re_xiaoqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["retianxiang", "hongyan"],
    names: "桥|null",
  },
  re_zhangjiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["releiji", "guidao", "huangtian"],
    isZhugong: true,
  },
  re_zhoutai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rebuqu", "fenji"],
  },
  re_yuji: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["reguhuo"],
  },
  re_shen_guanyu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["wushen", "wuhun"],
    groupInGuozhan: "shu",
  },
  re_shen_lvmeng: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["shelie", "gongxin"],
    groupInGuozhan: "wu",
  },
  re_dianwei: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reqiangxi"],
  },
  re_xunyu: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["quhu", "rejieming"],
    clans: ["颍川荀氏"],
  },
  re_pangtong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["relianhuan", "reniepan"],
  },
  re_sp_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["bazhen", "rehuoji", "rekanpo"],
    names: "诸葛|亮",
  },
  re_taishici: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["retianyi", "dangmo"],
    names: "太史|慈",
    dieAudios: ["ol_taishici"],
  },
  re_pangde: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["mashu", "jianchu"],
  },
  re_yanwen: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["reshuangxiong"],
    names: "颜|良-文|丑",
  },
  re_yuanshao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["reluanji", "xueyi"],
    isZhugong: true,
  },
  re_shen_zhouyu: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["qinyin", "yeyan"],
    groupInGuozhan: "wu",
  },
  re_shen_zhugeliang: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["qixing", "kuangfeng", "dawu"],
    groupInGuozhan: "shu",
    names: "诸葛|亮",
  },
  re_xuhuang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reduanliang", "jiezi"],
  },
  re_caopi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["rexingshang", "refangzhu", "songwei"],
    isZhugong: true,
  },
  re_sunjian: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["yinghun", "polu"],
  },
  re_dongzhuo: {
    sex: "male",
    group: "qun",
    hp: 8,
    skills: ["rejiuchi", "roulin", "benghuai", "rebaonue"],
    isZhugong: true,
  },
  re_zhurong: {
    sex: "female",
    group: "shu",
    hp: 4,
    skills: ["juxiang", "relieren"],
    names: "null|null",
  },
  re_menghuo: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["huoshou", "rezaiqi"],
  },
  re_jiaxu: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["rewansha", "reweimu", "luanwu"],
    dieAudios: ["ol_jiaxu"],
  },
  re_lusu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["rehaoshi", "redimeng"],
    dieAudios: ["ol_lusu"],
  },
  re_shen_caocao: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["guixin", "feiying"],
    groupInGuozhan: "wei",
  },
  re_shen_lvbu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["kuangbao", "wumou", "wuqian", "shenfen"],
    groupInGuozhan: "qun",
  },
  re_zhanghe: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reqiaobian"],
    dieAudios: ["ol_zhanghe"],
  },
  re_dengai: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["retuntian", "zaoxian"],
  },
  re_jiangwei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["retiaoxin", "rezhiji"],
  },
  re_liushan: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["xiangle", "refangquan", "ruoyu"],
    isZhugong: true,
  },
  re_sunce: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["jiang", "rehunzi", "zhiba"],
    isZhugong: true,
  },
  re_zhangzhang: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["rezhijian", "guzheng"],
    names: "张|昭-张|纮",
  },
  re_zuoci: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["rehuashen", "rexinsheng"],
  },
  re_caiwenji: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["rebeige", "duanchang"],
  },
  // wangji: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["qizhi", "jinqu"],
  // },
  // yanyan: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["juzhan"],
  // },
  // wangping: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["feijun", "binglve"],
  // },
  // luji: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["huaiju", "yili", "zhenglun"],
  //   clans: ["吴郡陆氏"],
  // },
  // sunliang: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["kuizhu", "zhizheng", "lijun"],
  //   isZhugong: true,
  // },
  // kuaiyuekuailiang: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 3,
  //   skills: ["jianxiang", "shenshi"],
  //   names: "蒯|良-蒯|越",
  // },
  // xuyou: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["chenglve", "shicai", "cunmu"],
  // },
  // luzhi: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["mingren", "zhenliang"],
  // },
  // guanqiujian: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["zhengrong", "hongju"],
  // },
  // chendao: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 4,
  //   skills: ["wanglie"],
  // },
  // zhugezhan: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["zuilun", "fuyin"],
  // },
  // zhoufei: {
  //   sex: "female",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["liangyin", "kongsheng"],
  // },
  // lukang: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["qianjie", "jueyan", "poshi"],
  //   clans: ["吴郡陆氏"],
  // },
  // zhangxiu: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["xiongluan", "congjian"],
  //   isZhugong: true,
  // },
  // haozhao: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["zhengu"],
  // },
  // yuanshu: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 4,
  //   skills: ["yongsi", "weidi"],
  //   isZhugong: true,
  // },
  // shen_zhouyu: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 4,
  //   skills: ["qinyin", "yeyan"],
  //   groupInGuozhan: "wu",
  // },
  // shen_zhugeliang: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 3,
  //   skills: ["qixing", "kuangfeng", "dawu"],
  //   groupInGuozhan: "shu",
  // },
  // shen_caocao: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 3,
  //   skills: ["guixin", "feiying"],
  //   groupInGuozhan: "wei",
  // },
  // shen_lvbu: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 5,
  //   skills: ["kuangbao", "wumou", "wuqian", "shenfen"],
  //   groupInGuozhan: "qun",
  // },
  // jshen_zhaoyun: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 2,
  //   skills: ["rejuejing", "relonghun"],
  //   groupInGuozhan: "shu",
  //   img: "image/character/shen_zhaoyun.jpg",
  //   dieAudios: ["shen_zhaoyun"],
  // },
  // jshen_simayi: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 4,
  //   skills: ["renjie", "sbaiyin", "lianpo"],
  //   groupInGuozhan: "wei",
  //   img: "image/character/shen_simayi.jpg",
  //   dieAudios: ["shen_simayi"],
  // },
  // le_liubei: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 6,
  //   skills: ["longnu", "jieying"],
  //   groupInGuozhan: "shu",
  // },
  // le_luxun: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 4,
  //   skills: ["junlve", "cuike", "zhanhuo"],
  //   groupInGuozhan: "wu",
  // },
  // le_zhangliao: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 4,
  //   skills: ["duorui", "zhiti"],
  //   groupInGuozhan: "wei",
  // },
  // le_ganning: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 3,
  //   maxHp: 6,
  //   skills: ["poxi", "ljieying"],
  //   groupInGuozhan: "wu",
  // },
}

export default characters
