export default {
  re_caoren: "大将军",
  re_xiahouyuan: "疾行的猎豹",
  re_huangzhong: "老当益壮",
  re_weiyan: "嗜血的独狼",
  re_xiaoqiao: "矫情之花",
  re_zhoutai: "历战之躯",
  re_zhangjiao: "天公将军",
  re_yuji: "太平青领道",
  re_shen_guanyu: "链狱鬼神",
  re_shen_lvmeng: "心生万象",

  re_dianwei: "古之恶来",
  re_xunyu: "王佐之才",
  re_sp_zhugeliang: "卧龙",
  re_pangtong: "凤雏",
  re_taishici: "剑鸣不平",
  re_pangde: "人马一体",
  re_yuanshao: "高贵的名门",
  re_yanwen: "虎狼兄弟",
  re_shen_zhouyu: "陵光引灵",
  re_shen_zhugeliang: "孟章诛邪",

  re_caopi: "霸业的继承者",
  re_xuhuang: "周亚夫之风",
  re_zhurong: "野性的女王",
  re_menghuo: "南蛮王",
  re_lusu: "荷檐吐奇",
  re_sunjian: "武烈帝",
  re_dongzhuo: "魔王",
  re_jiaxu: "毒士无双",
  re_shen_lvbu: "戾火浮屠",
  re_shen_caocao: "炼狱枭魂",

  re_dengai: "矫然的壮士",
  re_zhanghe: "无定的水虺",
  re_jiangwei: "龙的衣钵",
  re_liushan: "无为的真命主",
  re_sunce: "江东的小霸王",
  re_zhangzhang: "经天纬地",
  re_zuoci: "迷之仙人",
  re_caiwenji: "异乡的孤女",
  re_shen_simayi: "鉴往知来",
  re_shen_zhaoyun: "战龙在野",

  wangji: "经行合一",
  kuailiangkuaiyue: "雍论臼谋",
  yanyan: "断头将军",
  wangping: "兵谋以致用",
  luji: "瑚琏之器",
  sunliang: "寒江枯木",
  xuyou: "朝秦暮楚",
  luzhi: "国之桢干",
  shen_liubei: "誓守桃园义",
  shen_luxun: "红莲业火",

  haozhao: "扣弦的豪将",
  guanqiujian: "镌功铭征荣",
  chendao: "白毦督",
  zhugezhan: "临难死义",
  zhoufei: "软玉温香",
  lukang: "孤柱扶厦",
  yuanshu: "仲家帝",
  zhangxiu: "北地枪王",
  shen_zhangliao: "雁门之刑天",
  shen_ganning: "江表之力牧",
}
