const characterSort = {
  reshenhua_feng: [
    "re_caoren",
    "re_xiahouyuan",
    "re_huangzhong",
    "re_weiyan",
    "re_xiaoqiao",
    "re_zhoutai",
    "re_zhangjiao",
    "re_yuji",
    "shen_guanyu",
    "shen_lvmeng",
  ],
  reshenhua_huo: [
    "re_dianwei",
    "re_xunyu",
    "re_sp_zhugeliang",
    "re_pangtong",
    "re_taishici",
    "re_pangde",
    "re_yuanshao",
    "re_yanwen",
    "shen_zhouyu",
    "shen_zhugeliang",
  ],
  reshenhua_lin: [
    "re_caopi",
    "re_xuhuang",
    "re_menghuo",
    "re_zhurong",
    "re_sunjian",
    "re_dongzhuo",
    "re_lusu",
    "re_jiaxu",
    "shen_caocao",
    "shen_lvbu",
  ],
  reshenhua_shan: [
    "re_dengai",
    "re_jiangwei",
    "re_caiwenji",
    "re_zuoci",
    "re_sunce",
    "re_zhangzhang",
    "re_liushan",
    "re_zhanghe",
    "jshen_zhaoyun",
    "jshen_simayi",
  ],
  shenhua_yin: [
    "wangji",
    "yanyan",
    "wangping",
    "luji",
    "sunliang",
    "kuaiyuekuailiang",
    "xuyou",
    "luzhi",
    "le_liubei",
    "le_luxun",
  ],
  shenhua_lei: [
    "guanqiujian",
    "chendao",
    "zhugezhan",
    "zhoufei",
    "lukang",
    "zhangxiu",
    "haozhao",
    "yuanshu",
    "le_zhangliao",
    "le_ganning",
  ],
}

const characterSortTranslate = {
  reshenhua_feng: "界神话再临·风",
  reshenhua_huo: "界神话再临·火",
  reshenhua_lin: "界神话再临·林",
  reshenhua_shan: "界神话再临·山",
  shenhua_yin: "神话再临·阴",
  shenhua_lei: "神话再临·雷",
}

export { characterSort, characterSortTranslate }
