export default {
  "#rejushou1": "坚守此地，不退半步。",
  "#rejushou2": "兵精粮足，守土一方。",
  "#jiewei1": "坚壁清野，以挫敌锐。",
  "#jiewei2": "化守为攻，出奇制胜。",
  "#re_caoren:die": "长江以南，再无王土矣！",

  "#reshensu1": "吾等无需恋战。",
  "#reshensu2": "吾自当以一当十，速战速决。",
  "#re_xiahouyuan:die": "吾命休矣，遂成竖子之名。",

  "#reliegong1": "弓不离手，自有转机。",
  "#reliegong2": "箭阵开道，所向无敌。",
  "#re_huangzhong:die": "把我的弓，拿来，呃。",

  "#rekuanggu1": "哈哈哈……赢你还不容易？",
  "#rekuanggu2": "哼！也不看看我是何人！",
  "#qimou1": "成王败寇，怎可有勇无谋？",
  "#qimou2": "且不要因为暂时的得失而胆怯。",
  "#re_weiyan:die": "奸贼害我……",

  "#retianxiang1": "盈盈一笑，娇花照水。",
  "#retianxiang2": "月容花貌难自弃。",
  "#re_xiaoqiao:die": "周郎，等我！",

  "#rebuqu1": "战如熊虎，不惜躯命。",
  "#rebuqu2": "哼，这点小伤算什么。",
  "#fenji1": "百战之身，奋勇驱前。",
  "#fenji2": "两肋插刀，愿赴此躯。",
  "#re_zhoutai:die": "敌众我寡，无力回天。",

  "#releiji1": "成为黄天之世的祭品吧。",
  "#releiji2": "呼风唤雨，驱雷策电。",
  "#guidao_re_zhangjiao1": "道施所向，皆由我控。",
  "#guidao_re_zhangjiao2": "哼哼，天意如此。",
  "#huangtian_re_zhangjiao1": "苍天不覆，黄天交替。",
  "#huangtian_re_zhangjiao2": "黄天立，民心顺，天下平。",
  "#re_zhangjiao:die": "黄天既覆，苍生何存……",

  "#reguhuo1": "道法玄机，变幻莫测。",
  "#reguhuo2": "如真似幻，扑朔迷离。",
  "#chanyuan1": "不识天数，在劫难逃。",
  "#chanyuan2": "凡人仇怨，皆由心生。",
  "#re_yuji:die": "道法玄机，竟被参破……",

  "#reqiangxi1": "铁戟双提八十斤，威风凛凛震乾坤！",
  "#reqiangxi2": "勇字当头，义字当先！",
  "#re_dianwei:die": "汝等小儿，竟敢害我！拿命来！",

  "#quhu_re_xunyu1": "驱虎伤敌，保我无虞。",
  "#quhu_re_xunyu2": "无需费我一兵一卒。",
  "#rejieming1": "因势利导，是为良计。",
  "#rejieming2": "杀身成仁，不负皇恩。",
  "#re_xunyu:die": "命不由人，徒叹奈何……",

  "#bazhen_re_sp_zhugeliang1": "你可识得此阵？",
  "#bazhen_re_sp_zhugeliang2": "太极生两仪，两仪生四象，四象生八卦。",
  "#rehuoji1": "燃烧吧！",
  "#rehuoji2": "此火可助我军大获全胜。",
  "#rekanpo1": "雕虫小技！",
  "#rekanpo2": "你的计谋被识破了！",
  "#re_sp_zhugeliang:die": "我的计谋竟被……",

  "#relianhuan1": "将多兵众，不可以敌，使其自累，以杀其势。",
  "#relianhuan2": "善用兵者，运巧必防损，立谋虑中变。",
  "#reniepan1": "凤凰折翅，涅槃再生。",
  "#reniepan2": "九天之志，展翅翱翔。",
  "#re_pangtong:die": "落……凤……坡……",

  "#dangmo1": "魔高一尺，道高一丈！",
  "#dangmo2": "天魔祸世，吾自荡而除之！",

  "#jianchu1": "来呀，冲杀出去，杀他个片甲不留。",
  "#jianchu2": "一人一骑，横扫千军。",
  "#re_pangde:die": "我宁为国家鬼，不为贼将也。",

  "#reluanji1": "万箭穿心，灭其士气。",
  "#reluanji2": "卿当与本公同心戮力，共安社稷。",
  "#xueyi_re_yuanshao1": "名门士胄，朝野敬仰。",
  "#xueyi_re_yuanshao2": "吾乃名门望族，岂能与汝等为伍？",
  "#re_yuanshao:die": "袁门不幸啊……",

  "#reshuangxiong1": "此战，如有你我一人在此，何惧华雄？定叫他有去无回！",
  "#reshuangxiong2": "哥哥，且看我与赵云一战。且与他战个五十回合！",
  "#re_yanwen:die": "不是叫你看好我身后吗？",

  "#rexingshang1": "群燕辞归鹄南翔，念君客游思断肠。",
  "#rexingshang2": "霜露纷兮交下，木叶落兮凄凄。",
  "#refangzhu1": "国法不可废耳，汝先退去。",
  "#refangzhu2": "将军征战辛苦，孤当赠以良宅。",
  "#songwei_re_caopi1": "藩屏大宗，御侮厌难。",
  "#songwei_re_caopi2": "朕承符运，受终革命。",
  "#re_caopi:die": "建平所言八十，谓昼夜也，吾其决矣……",

  "#reduanliang1": "粮不三载，敌军已犯行军大忌。",
  "#reduanliang2": "断敌粮秣，此战可胜。",
  "#jiezi1": "因粮于敌，敌军食可足也。",
  "#jiezi2": "食敌一钟，当吾二十钟。",
  "#re_xuhuang:die": "敌军防备周全，是吾轻敌……",

  "#juxiang_re_zhurong1": "今日就让这群汉人长长见识。",
  "#juxiang_re_zhurong2": "我的大象终于有了用武之地。",
  "#relieren1": "有我手中飞刀在，何惧蜀军！",
  "#relieren2": "长矛，飞刀，烈火，都来吧！",
  "#re_zhurong:die": "这群汉人使诈……",

  "#huoshou_re_menghuo1": "汉人，岂是我等的对手。",
  "#huoshou_re_menghuo2": "定叫你们有来无回！",
  "#rezaiqi1": "胜败乃常事，无妨！",
  "#rezaiqi2": "汉人奸诈，还是不服，再战！",
  "#re_menghuo:die": "我一定要赢，要赢啊……",

  "#yinghun_re_sunjian1": "义定四野，武匡海内。",
  "#yinghun_re_sunjian2": "江东男儿，皆胸怀匡扶天下之志。",
  "#polu1": "斩敌复城，扬我江东军威！",
  "#re_sunjian:die": "吾身虽死，忠勇须传。",

  "#rejiuchi1": "无酒不欢，来来来，再饮，再饮！",
  "#rejiuchi2": "黄金美酒夜光杯，舍我其谁啊，哈哈哈哈哈哈！",
  "#roulin_re_dongzhuo1": "美女，美酒，美食，嘿嘿，尽我享用！",
  "#roulin_re_dongzhuo2": "嗯啊，尽享天下美味，哼哼哼哼哈哈哈哈！",
  "#benghuai_re_dongzhuo1": "什么礼制纲常，我说的就是纲常！",
  "#benghuai_re_dongzhuo2": "谁有权力，谁掌生死！",
  "#rebaonue1": "不施严法，怎治乱民，休得啰嗦！",
  "#rebaonue2": "天子在我手里，我怕谁！",
  "#re_dongzhuo:die": "竖子，竟敢反我！",

  "#retuntian1": "休养生息，是为以备不虞。",
  "#retuntian2": "战损难免，应以军务减之。",
  "#zaoxian_re_dengai1": "用兵以险，则战之以胜！",
  "#zaoxian_re_dengai2": "已至马阁山，宜速进军破蜀！",
  "#jixi_re_dengai1": "攻敌之不备，斩将夺辎！",
  "#jixi_re_dengai2": "奇兵正攻，敌何能为？",
  "#re_dengai:die": "一片忠心，换来这般田地。",

  "#retiaoxin1": "黄口竖子，何必上阵送命？",
  "#retiaoxin2": "汝如欲大败而归，则可进军一战！",
  "#rezhiji1": "维定当奋身以复汉室。",
  "#rezhiji2": "丞相之志，维必竭力而为。",
  "#reguanxing_re_jiangwei1": "知天易则观之，逆天难亦行之。",
  "#reguanxing_re_jiangwei2": "欲尽人事，亦先听天命。",
  "#re_jiangwei:die": "可惜大计未成，吾已身陨。",

  "#xiangle_re_liushan1": "天府之国，自然民安国泰。",
  "#xiangle_re_liushan2": "战事扰乱民生，不如作罢。",
  "#refangquan1": "爱卿自行定夺便是。",
  "#refangquan2": "北伐事重，相父全权处理即可。",
  "#ruoyu_re_liushan1": "唯有自认庸主之名，方能保蜀地官民无虞啊。",
  "#ruoyu_re_liushan2": "既无争雄天下之才，只好做守成之主。",
  "#jijiang_re_liushan1": "还望诸卿勠力同心，以保国祚。",
  "#jijiang_re_liushan2": "哪位爱卿愿意报效国家？",
  "#re_liushan:die": "实在有愧父皇与相父啊……",

  "#jiang_re_sunce1": "我会把胜利带回江东。",
  "#jiang_re_sunce2": "天下英雄，谁能与我一战？",
  "#rehunzi1": "小霸王之名响彻天下，何人不知？",
  "#rehunzi2": "江东已平，中原动荡，直取许昌。",
  "#zhiba_re_sunce1": "我的霸业才刚刚开始。",
  "#zhiba_re_sunce2": "汝是战是降，我皆奉陪。",
  "#reyingzi_re_sunce1": "有公瑾助我，可平天下。",
  "#reyingzi_re_sunce2": "所到之处，战无不胜。",
  "#yinghun_re_sunce1": "武烈之魂，助我扬名。",
  "#yinghun_re_sunce2": "江东之主，众望所归。",
  "#re_sunce:die": "大业未就，中世尔殒……",

  "#rezhijian1": "为臣之道，在于直言无讳。",
  "#rezhijian2": "忠言或逆耳，于国无一害。",
  "#guzheng_re_zhangzhang1": "为君者，不可肆兴土木，奢费物力。",
  "#guzheng_re_zhangzhang2": "安民固国，方可思动。",
  "#re_zhangzhang:die": "只恨不能为东吴百姓再谋一日福祉……",

  "#rehuashen1": "世间万物，贫道皆可化为其形。",
  "#rehuashen2": "尘身土塑，唯魂魄难得。",
  "#rexinsheng1": "大成若缺，损亦无妨。",
  "#rexinsheng2": "大盈若冲，新神自现。",
  "#re_zuoci:die": "仙人之逝，魂归九天。",

  "#rebeige1": "人多暴猛兮如虺蛇，控弦披甲兮为骄奢。",
  "#rebeige2": "两拍张弦兮弦欲绝，志摧心折兮自悲嗟。",
  "#duanchang_re_caiwenji1": "雁高飞兮邈难寻，空断肠兮思愔愔。",
  "#duanchang_re_caiwenji2": "为天有眼兮，为何使我独飘流？",
  "#re_caiwenji:die": "今别子兮归故乡，旧怨平兮新怨长！",

  "#rejuejing1": "绝望中…仍存有一线生机！",
  "#rejuejing2": "还不可以认输！",
  "#relonghun1": "龙战于野，其血玄黄！",
  "#relonghun2": "潜龙勿用，藏锋守拙。",
  "#re_shen_zhaoyun:die": "龙磷崩损，坠于九天…",

  "#qizhi1": "声东击西，敌寇一网成擒。",
  "#qizhi2": "吾意不在此地，已遣别部出发。",
  "#jinqu1": "通川聚粮，伐吴之业，当步步为营。",
  "#jinqu2": "建上昶水城，以逼夏口。",
  "#wangji:die": "天下之势，必归大魏。可恨，未能得见哪……",

  "#jianxiang1": "得遇曹公，吾之幸也。",
  "#jianxiang2": "曹公得荆不喜，喜得吾二人足矣。",
  "#shenshi1": "深中足智，鉴时审情。",
  "#shenshi2": "数语之言，审时度势。",
  "#kuailiangkuaiyue:die": "表不能善用，所憾也。",

  "#juzhan1": "砍头便砍头，何为怒邪。",
  "#juzhan2": "我州但有断头将军，无降将军也。",
  "#yanyan:die": "宁可断头死，安能屈膝降？",

  "#feijun1": "无当飞军，伐叛乱，镇蛮夷！",
  "#feijun2": "山地崎岖，也挡不住飞军破势！",
  "#binglve1": "奇略兵速，敌未能料之。",
  "#binglve2": "兵略者，明战胜攻取之数，形机之势，诈谲之变。",
  "#wangping:die": "无当飞军，也有困于山林之时。",

  "#huaiju1": "情深舐犊，怀擢藏橘。",
  "#huaiju2": "袖中怀绿桔，遗母报乳哺。",
  "#yili1": "行遗礼之举，于不敬王者。",
  "#yili2": "违失礼仪，则俱非议。",
  "#zhenglun1": "整论四海未泰，修文德以平。",
  "#zhenglun2": "今论者不务道德怀取之术，而惟尚武，窃所未安。",
  "#luji:die": "恨不能见，车同轨，书同文……",

  "#kuizhu1": "子通专恣，必谋而诛之！",
  "#kuizhu2": "孙綝久专，不可久忍，必溃诛！",
  "#chezheng1": "风驰电掣，政权不怠！",
  "#chezheng2": "唉，廉平掣政，实为艰事。",
  "#lijun1": "立于朝堂，定于军心。",
  "#lijun2": "君立于朝堂，军策于四方！",
  "#sunliang:die": "今日欲诛逆臣而不得，方知机事不密则害成……",

  "#chenglve1": "成略在胸，良计速出。",
  "#chenglve2": "吾有良略在怀，必为阿瞒所需。",
  "#shicai1": "吾才满腹，袁本初竟不从之！",
  "#shicai2": "阿瞒有我良计，取冀州便是易如反掌。",
  "#cunmu1": "目光所及，短寸之间。",
  "#cunmu2": "狭目之见，只能窥底。",
  "#xuyou:die": "阿瞒，没有我，你得不到冀州啊！",

  "#mingren1": "吾之任，君之明举！",
  "#mingren2": "得义真所救，吾任之必尽瘁以报。",
  "#zhenliang1": "贞洁贤良，吾之本心。",
  "#zhenliang2": "风霜以别草木之性，危乱而见贞良之节。",
  "#luzhi:die": "泓泓眸子宿渊亭，不见蛾眉只见经。",

  "#longnu1": "兄弟疾难，血债血偿！",
  "#longnu2": "损身熬心，誓报此仇！",
  "#jieying1": "结草衔环，报兄弟大恩。",
  "#jieying2": "桃园结义，营一世之交。",
  "#shen_liubei:die": "桃园依旧，来世再结……",

  "#junlve1": "军略绵腹，制敌千里。",
  "#junlve2": "文韬武略兼备，方可破敌如破竹。",
  "#cuike1": "摧敌心神，克敌计谋。",
  "#cuike2": "克险摧难，军略当先。",
  "#zhanhuo1": "业火映东水，吴志绽敌营。",
  "#zhanhuo2": "绽东吴业火，烧敌军数千。",
  "#shen_luxun:die": "东吴业火，终究熄灭。",

  "#drlt_zhengu1": "镇守城池，必以骨相拼！",
  "#drlt_zhengu2": "孔明计虽百算，却难敌吾镇骨千具！",
  "#haozhao:die": "镇守陈仓，也有一失。",

  "#drlt_zhenrong1": "东征高句丽，保辽东安稳。",
  "#drlt_zhenrong2": "跨海东征，家国俱荣。",
  "#drlt_hongju1": "一举拿下，鸿途可得。",
  "#drlt_hongju2": "鸿飞荣升，举重若轻。",
  "#drlt_qingce1": "感明帝之恩，清君侧之贼。",
  "#drlt_qingce2": "得太后手诏，清奸佞乱臣。",
  "#guanqiujian:die": "峥嵘一生，然被平民所击射！",

  "#drlt_wanglie1": "猛将之烈，统帅之所往。",
  "#drlt_wanglie2": "与子龙忠勇相往，猛烈相合。",
  "#chendao:die": "我的白毦兵，再也不能为先帝出力了。",

  "#xinfu_zuilun1": "吾有三罪，未能除黄皓、制伯约、守国土。",
  "#xinfu_zuilun2": "数罪当论，吾愧对先帝恩惠。",
  "#xinfu_fuyin1": "得父荫庇，平步青云。",
  "#xinfu_fuyin2": "吾自幼心怀父诫，方不愧父亲荫庇。",
  "#zhugezhan:die": "临难而死义，无愧先父。",

  "#liangyin1": "结得良姻，固吴基业。",
  "#liangyin2": "君恩之命，妾身良姻之福。",
  "#kongsheng1": "窈窕淑女，箜篌有知。",
  "#kongsheng2": "箜篌声声，琴瑟和鸣。",
  "#zhoufei:die": "夫君，妾身再也不能陪你看这江南翠绿了。",

  "#drlt_qianjie1": "继父之节，谦逊恭毕。",
  "#drlt_qianjie2": "谦谦清廉德，节节卓尔茂。",
  "#drlt_jueyan1": "毁堰坝之计，实为阻晋粮道。",
  "#drlt_jueyan2": "堰坝毁之，可令敌军自退。",
  "#drlt_poshi1": "破晋军分进合击之势，牵晋军主力之实！",
  "#drlt_poshi2": "破羊祜之策，势在必行！",
  "#rejizhi_lukang1": "智父，安能有愚子乎？",
  "#drlt_huairou1": "各保分界，无求细利。",
  "#drlt_huairou2": "胸怀千万，彰其德，包其柔。",
  "#lukang:die": "吾即亡矣，吴又能存几时……",

  "#yongsi1": "朕今日雄踞淮南，明日便可一匡天下。",
  "#yongsi2": "天下，即将尽归吾袁公路！",
  "#weidi1": "传朕旨意，诸部遵旨即可。",
  "#weidi2": "传国玉玺在手，朕语便是天言。",
  "#yuanshu:die": "仲朝国祚，本应千秋万代，薪传不息……",

  "#xiongluan1": "北地枭雄，乱世不败。",
  "#xiongluan2": "雄踞宛城，虽乱世可安。",
  "#congjian1": "从谏良计，可得自保。",
  "#congjian2": "听君谏言，去危亡，保宗祀。",
  "#zhangxiu:die": "若失文和，吾将何归？",

  "#duorui1": "夺敌军锐气，杀敌方士气。",
  "#duorui2": "尖锐之势，吾亦可一人夺之！",
  "#zhiti1": "娃闻名止啼，孙损十万休。",
  "#zhiti2": "江东小儿，安敢啼哭？",
  "#shen_zhangliao:die": "我也有被孙仲谋所伤之时？",

  "#poxi1": "夜袭敌军，挫其锐气。",
  "#poxi2": "受主知遇，袭敌不惧。",
  "#gn_jieying1": "劫营速战，措手不及。",
  "#gn_jieying2": "裹甲衔枚，劫营如入无人之境。",
  "#shen_ganning:die": "吾不能奉主，谁辅主基业？",
}
