const characters = {
  ol_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejianxiong", "rehujia"],
    isZhugong: true,
    img: "image/character/re_caocao.jpg",
    dieAudios: ["re_caocao"],
  },
  re_simayi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["refankui", "reguicai"],
    names: "司马|懿",
  },
  ol_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olganglie", "qingjian"],
    names: "夏侯|惇",
    img: "image/character/re_xiahoudun.jpg",
    dieAudios: ["re_xiahoudun"],
  },
  re_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["retuxi"],
  },
  ol_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olluoyi"],
    img: "image/character/re_xuzhu.jpg",
    dieAudios: ["re_xuzhu"],
  },
  re_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "reyiji"],
  },
  ol_zhenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["reluoshen", "qingguo"],
    img: "image/character/re_zhenji.jpg",
    dieAudios: ["re_zhenji"],
  },
  ol_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rerende", "rejijiang"],
    isZhugong: true,
    img: "image/character/re_liubei.jpg",
    dieAudios: ["re_liubei"],
  },
  re_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rewusheng", "yijue"],
  },
  ol_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["olpaoxiao", "retishen"],
    img: "image/character/re_zhangfei.jpg",
    dieAudios: ["re_zhangfei"],
  },
  re_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["reguanxing", "kongcheng"],
    names: "诸葛|亮",
  },
  ol_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["relongdan", "reyajiao"],
    img: "image/character/re_zhaoyun.jpg",
    dieAudios: ["re_zhaoyun"],
  },
  re_machao: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "retieji"],
  },
  ol_huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["oljizhi", "reqicai"],
    img: "image/character/re_huangyueying.jpg",
    dieAudios: ["re_huangyueying"],
  },
  ol_sunquan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rezhiheng", "oljiuyuan"],
    isZhugong: true,
    img: "image/character/re_sunquan.jpg",
    dieAudios: ["re_sunquan"],
  },
  re_ganning: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["qixi", "fenwei"],
  },
  ol_lvmeng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["keji", "reqinxue", "botu"],
    img: "image/character/re_lvmeng.jpg",
    dieAudios: ["re_lvmeng"],
  },
  ol_huanggai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rekurou", "rezhaxiang"],
    img: "image/character/re_huanggai.jpg",
    dieAudios: ["re_huanggai"],
  },
  re_zhouyu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reyingzi", "refanjian"],
  },
  re_daqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["reguose", "liuli"],
    names: "桥|null",
  },
  re_luxun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reqianxun", "relianying"],
    clans: ["吴郡陆氏"],
  },
  ol_sunshangxiang: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["rejieyin", "xiaoji"],
    img: "image/character/re_sunshangxiang.jpg",
    dieAudios: ["re_sunshangxiang"],
  },
  re_huatuo: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jijiu", "chuli"],
  },
  re_lvbu: {
    sex: "male",
    group: "qun",
    hp: 5,
    skills: ["wushuang", "liyu"],
  },
  ol_diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["relijian", "rebiyue"],
    names: "null|null",
    img: "image/character/diaochan.jpg",
    dieAudios: ["diaochan"],
  },
  ol_huaxiong: {
    sex: "male",
    group: "qun",
    hp: 6,
    skills: ["olyaowu", "shizhan"],
    img: "image/character/re_huaxiong.jpg",
  },
  ol_gongsunzan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["reyicong", "reqiaomeng"],
    img: "image/character/re_gongsunzan.jpg",
    dieAudios: ["re_gongsunzan"],
  },
  ol_caoren: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejushou", "rejiewei"],
    img: "image/character/re_caoren.jpg",
    dieAudios: ["re_caoren"],
  },
  ol_xiahouyuan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reshensu", "shebian"],
    names: "夏侯|渊",
  },
  ol_huangzhong: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["olliegong"],
  },
  ol_weiyan: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rekuanggu", "reqimou"],
  },
  ol_xiaoqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["oltianxiang", "rehongyan", "piaoling"],
    names: "桥|null",
  },
  ol_zhoutai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["olbuqu", "refenji"],
    img: "image/character/re_zhoutai.jpg",
    dieAudios: ["re_zhoutai"],
  },
  ol_zhangjiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["olleiji", "reguidao", "rehuangtian"],
    isZhugong: true,
  },
  ol_yuji: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["olguhuo"],
  },
  ol_shen_guanyu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["rewushen", "wuhun"],
    groupInGuozhan: "shu",
    img: "image/character/shen_guanyu.jpg",
    dieAudios: ["shen_guanyu"],
  },
  shen_lvmeng: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["shelie", "gongxin"],
    groupInGuozhan: "wu",
  },
  ol_dianwei: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olqiangxi", "ninge"],
  },
  ol_xunyu: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["quhu", "oljieming"],
    clans: ["颍川荀氏"],
  },
  ol_sp_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["bazhen", "olhuoji", "olkanpo", "cangzhuo"],
    names: "诸葛|亮",
  },
  ol_pangtong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["ollianhuan", "olniepan"],
  },
  ol_taishici: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["tianyi", "hanzhan"],
    names: "太史|慈",
    dieAudios: ["re_taishici"],
  },
  ol_pangde: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["mashu", "rejianchu"],
  },
  ol_yuanshao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["olluanji", "rexueyi"],
    isZhugong: true,
  },
  ol_yanwen: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["olshuangxiong"],
    names: "颜|良-文|丑",
  },
  shen_zhouyu: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["qinyin", "yeyan"],
    groupInGuozhan: "wu",
  },
  shen_zhugeliang: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["qixing", "kuangfeng", "dawu"],
    groupInGuozhan: "shu",
    names: "诸葛|亮",
  },
  re_caopi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["rexingshang", "refangzhu", "songwei"],
    isZhugong: true,
  },
  ol_xuhuang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olduanliang", "rejiezi"],
  },

  ol_jiangwei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["oltiaoxin", "olzhiji"],
  },
}

export default characters
