const characters = {
  ol_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejianxiong", "rehujia"],
    isZhugong: true,
    img: "image/character/re_caocao.jpg",
    dieAudios: ["re_caocao"],
  },
  re_simayi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["refankui", "reguicai"],
    names: "司马|懿",
  },
  re_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reganglie", "qingjian"],
    names: "夏侯|惇",
  },
  re_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["retuxi"],
  },
  ol_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olluoyi"],
    img: "image/character/re_xuzhu.jpg",
    dieAudios: ["re_xuzhu"],
  },
  re_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "reyiji"],
  },
  ol_zhenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["reluoshen", "qingguo"],
    img: "image/character/re_zhenji.jpg",
    dieAudios: ["re_zhenji"],
  },
  ol_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rerende", "rejijiang"],
    isZhugong: true,
    img: "image/character/re_liubei.jpg",
    dieAudios: ["re_liubei"],
  },
  re_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rewusheng", "yijue"],
  },
  ol_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["olpaoxiao", "retishen"],
    img: "image/character/re_zhangfei.jpg",
    dieAudios: ["re_zhangfei"],
  },
  re_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["reguanxing", "kongcheng"],
    names: "诸葛|亮",
  },
  ol_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["relongdan", "reyajiao"],
    img: "image/character/re_zhaoyun.jpg",
    dieAudios: ["re_zhaoyun"],
  },
  re_machao: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "retieji"],
  },
  ol_huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["oljizhi", "reqicai"],
    img: "image/character/re_huangyueying.jpg",
    dieAudios: ["re_huangyueying"],
  },
  xushu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["zhuhai", "qianxin"],
  },
  re_sunquan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rezhiheng", "rejiuyuan"],
    isZhugong: true,
  },
  re_ganning: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["qixi", "fenwei"],
  },
  re_lvmeng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["keji", "qinxue"],
  },
  re_huanggai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rekurou", "zhaxiang"],
  },
  re_zhouyu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reyingzi", "refanjian"],
  },
  re_daqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["reguose", "liuli"],
    names: "桥|null",
  },
  re_luxun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reqianxun", "relianying"],
    clans: ["吴郡陆氏"],
  },
  re_sunshangxiang: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["rejieyin", "rexiaoji"],
  },
  re_huatuo: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jijiu", "chuli"],
  },
  re_lvbu: {
    sex: "male",
    group: "qun",
    hp: 5,
    skills: ["wushuang", "liyu"],
  },
  re_diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["lijian", "rebiyue"],
    names: "null|null",
  },
  re_huaxiong: {
    sex: "male",
    group: "qun",
    hp: 6,
    skills: ["reyaowu"],
  },
  re_gongsunzan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["qiaomeng", "yicong"],
  },
}

export default characters
