const characters = {
  ol_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejianxiong", "rehujia"],
    isZhugong: true,
    img: "image/character/re_caocao.jpg",
    dieAudios: ["re_caocao"],
  },
  re_simayi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["refankui", "reguicai"],
    names: "司马|懿",
  },
  re_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reganglie", "qingjian"],
    names: "夏侯|惇",
  },
  re_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["retuxi"],
  },
  ol_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["olluoyi"],
    img: "image/character/re_xuzhu.jpg",
    dieAudios: ["re_xuzhu"],
  },
  re_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "reyiji"],
  },
  ol_zhenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["reluoshen", "qingguo"],
    img: "image/character/re_zhenji.jpg",
    dieAudios: ["re_zhenji"],
  },
  ol_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rerende", "rejijiang"],
    isZhugong: true,
    img: "image/character/re_liubei.jpg",
    dieAudios: ["re_liubei"],
  },
  re_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rewusheng", "yijue"],
  },
  ol_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["olpaoxiao", "retishen"],
    img: "image/character/re_zhangfei.jpg",
    dieAudios: ["re_zhangfei"],
  },
  re_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["reguanxing", "kongcheng"],
    names: "诸葛|亮",
  },
  ol_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["relongdan", "reyajiao"],
    img: "image/character/re_zhaoyun.jpg",
    dieAudios: ["re_zhaoyun"],
  },
  re_machao: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "retieji"],
  },
  ol_huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["oljizhi", "reqicai"],
    img: "image/character/re_huangyueying.jpg",
    dieAudios: ["re_huangyueying"],
  },
  ol_sunquan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rezhiheng", "oljiuyuan"],
    isZhugong: true,
    img: "image/character/re_sunquan.jpg",
    dieAudios: ["re_sunquan"],
  },
  re_ganning: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["qixi", "fenwei"],
  },
  ol_lvmeng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["keji", "reqinxue", "botu"],
    img: "image/character/re_lvmeng.jpg",
    dieAudios: ["re_lvmeng"],
  },
  ol_huanggai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rekurou", "rezhaxiang"],
    img: "image/character/re_huanggai.jpg",
    dieAudios: ["re_huanggai"],
  },
  re_zhouyu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reyingzi", "refanjian"],
  },
  re_daqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["reguose", "liuli"],
    names: "桥|null",
  },
  re_luxun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["reqianxun", "relianying"],
    clans: ["吴郡陆氏"],
  },
  ol_sunshangxiang: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["rejieyin", "xiaoji"],
    img: "image/character/re_sunshangxiang.jpg",
    dieAudios: ["re_sunshangxiang"],
  },
  re_huatuo: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jijiu", "chuli"],
  },
  re_lvbu: {
    sex: "male",
    group: "qun",
    hp: 5,
    skills: ["wushuang", "liyu"],
  },
  ol_diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["relijian", "rebiyue"],
    names: "null|null",
    img: "image/character/diaochan.jpg",
    dieAudios: ["diaochan"],
  },
  ol_huaxiong: {
    sex: "male",
    group: "qun",
    hp: 6,
    skills: ["olyaowu", "shizhan"],
    img: "image/character/re_huaxiong.jpg",
    dieAudios: ["re_huaxiong"],
  },
  ol_gongsunzan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["reyicong", "reqiaomeng"],
    img: "image/character/re_gongsunzan.jpg",
    dieAudios: ["re_gongsunzan"],
  },
  ol_caoren: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["rejushou", "rejiewei"],
    img: "image/character/re_caoren.jpg",
    dieAudios: ["re_caoren"],
  },
  ol_xiahouyuan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reshensu", "shebian"],
    names: "夏侯|渊",
  },
  ol_huangzhong: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["olliegong"],
  },
  ol_weiyan: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rekuanggu", "reqimou"],
  },
  ol_xiaoqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["oltianxiang", "rehongyan", "piaoling"],
    names: "桥|null",
  },
  ol_zhoutai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["rebuqu", "refenji"],
    img: "image/character/re_zhoutai.jpg",
    dieAudios: ["re_zhoutai"],
  },
}

export default characters
