const characterSort = {
  refresh_standard: [
    "ol_caocao",
    "re_simayi",
    "re_xiahoudun",
    "re_zhangliao",
    "ol_xuzhu",
    "re_guojia",
    "ol_zhenji",
    "ol_liubei",
    "re_guanyu",
    "ol_zhangfei",
    "ol_zhaoyun",
    "re_machao",
    "re_zhouyu",
    "re_lvmeng",
    "re_ganning",
    "re_luxun",
    "re_daqiao",
    "re_huanggai",
    "re_lvbu",
    "re_huatuo",
    "re_diaochan",
    "re_huangyueying",
    "re_sunquan",
    "re_sunshangxiang",
    "re_zhugeliang",
    "re_huaxiong",
    "re_gongsunzan",
    "re_lidian",
    "re_xushu",
  ],
  refresh_feng: [
    "caoren",
    "ol_xiahouyuan",
    "ol_weiyan",
    "ol_xiaoqiao",
    "zhoutai",
    "re_zhangjiao",
    "xin_yuji",
    "ol_huangzhong",
  ],
  refresh_huo: [
    "ol_sp_zhugeliang",
    "ol_xunyu",
    "ol_dianwei",
    "ol_yanwen",
    "ol_pangtong",
    "ol_yuanshao",
    "ol_pangde",
    "re_taishici",
  ],
  refresh_lin: [
    "re_menghuo",
    "ol_sunjian",
    "re_caopi",
    "ol_xuhuang",
    "ol_dongzhuo",
    "ol_zhurong",
    "re_jiaxu",
    "ol_lusu",
  ],
  refresh_shan: [
    "ol_jiangwei",
    "ol_caiwenji",
    "ol_liushan",
    "ol_zhangzhang",
    "re_zuoci",
    "re_sunce",
    "ol_dengai",
    "re_zhanghe",
  ],
}

const characterSortTranslate = {
  refresh_standard: "界限突破·标",
  refresh_feng: "界限突破·风",
  refresh_huo: "界限突破·火",
  refresh_lin: "界限突破·林",
  refresh_shan: "界限突破·山",
}

export { characterSort, characterSortTranslate }
