const characterSort = {
  shenwu_standard: [
    "ol_caocao",
    "ol_simayi",
    "ol_xiahoudun",
    "ol_zhangliao",
    "ol_xuzhu",
    "ol_guojia",
    "ol_zhenji",

    "ol_liubei",
    "ol_guanyu",
    "ol_zhangfei",
    "ol_zhugeliang",
    "ol_zhaoyun",
    "ol_machao",
    "ol_huangyueying",

    "ol_sunquan",
    "ol_ganning",
    "ol_lvmeng",
    "ol_huanggai",
    "ol_zhouyu",
    "ol_daqiao",
    "ol_luxun",
    "ol_sunshangxiang",

    "ol_huatuo",
    "ol_lvbu",
    "ol_diaochan",
    "ol_huaxiong",
    "ol_gongsunzan",
  ],
  shenwu_feng: [
    "ol_caoren",
    "ol_xiahouyuan",
    "ol_huangzhong",
    "ol_weiyan",
    "ol_xiaoqiao",
    "ol_zhoutai",
    "ol_zhangjiao",
    "ol_yuji",
    "ol_shen_guanyu",
    "ol_shen_lvmeng",
  ],
  shenwu_huo: [
    "ol_dianwei",
    "ol_xunyu",
    "ol_sp_zhugeliang",
    "ol_pangtong",
    "ol_taishici",
    "ol_pangde",
    "ol_yuanshao",
    "ol_yanwen",
    "ol_shen_zhouyu",
    "ol_shen_zhugeliang",
  ],
  shenwu_lin: [
    "ol_caopi",
    "ol_xuhuang",
    "ol_zhurong",
    "ol_menghuo",
    "ol_lusu",
    "ol_sunjian",
    "ol_dongzhuo",
    "ol_jiaxu",
    "ol_shen_lvbu",
    "ol_shen_caocao",
  ],
  shenwu_shan: [
    "ol_dengai",
    "ol_zhanghe",
    "ol_jiangwei",
    "ol_liushan",
    "ol_sunce",
    "ol_zhangzhang",
    "ol_zuoci",
    "ol_caiwenji",
    "ol_shen_simayi",
    "ol_shen_zhaoyun",
  ],
  shenwu_yin: [
    "wangji",
    "kuaiyuekuailiang",
    "yanyan",
    "wangping",
    "luji",
    "sunliang",
    "xuyou",
    "luzhi",
    "le_liubei",
    "le_luxun",
  ],
  shenwu_lei: [
    "haozhao",
    "guanqiujian",
    "chendao",
    "zhugezhan",
    "zhoufei",
    "lukang",
    "yuanshu",
    "zhangxiu",
    "le_zhangliao",
    "le_ganning",
  ],
}

const characterSortTranslate = {
  shenwu_standard: "神武再世·标",
  shenwu_feng: "神武再世·风",
  shenwu_huo: "神武再世·火",
  shenwu_lin: "神武再世·林",
  shenwu_shan: "神武再世·山",
}

export { characterSort, characterSortTranslate }
