const characterSort = {
  refresh_standard: [
    "ol_caocao",
    "re_simayi",
    "ol_xiahoudun",
    "re_zhangliao",
    "ol_xuzhu",
    "re_guojia",
    "ol_zhenji",

    "ol_liubei",
    "re_guanyu",
    "ol_zhangfei",
    "re_zhugeliang",
    "ol_zhaoyun",
    "re_machao",
    "ol_huangyueying",

    "ol_sunquan",
    "re_ganning",
    "ol_lvmeng",
    "ol_huanggai",
    "re_zhouyu",
    "re_daqiao",
    "re_luxun",
    "ol_sunshangxiang",

    "re_huatuo",
    "re_lvbu",
    "ol_diaochan",
    "ol_huaxiong",
    "ol_gongsunzan",
  ],
  refresh_feng: [
    "ol_caoren",
    "ol_xiahouyuan",
    "ol_huangzhong",
    "ol_weiyan",
    "ol_xiaoqiao",
    "ol_zhoutai",
    "ol_zhangjiao",
    "ol_yuji",
    "ol_shen_guanyu",
    "shen_lvmeng",
  ],
  refresh_huo: [
    "ol_dianwei",
    "ol_xunyu",
    "ol_sp_zhugeliang",
    "ol_pangtong",
    "ol_taishici",
    "ol_pangde",
    "ol_yuanshao",
    "ol_yanwen",
    "shen_zhouyu",
    "shen_zhugeliang",
  ],
  refresh_lin: [
    "re_caopi",
    "ol_xuhuang",
    "ol_zhurong",
    "ol_menghuo",
    "ol_sunjian",
    "ol_dongzhuo",
    "re_jiaxu",
    "ol_lusu",
  ],
  refresh_shan: [
    "ol_jiangwei",
    "ol_caiwenji",
    "ol_liushan",
    "ol_zhangzhang",
    "re_zuoci",
    "re_sunce",
    "ol_dengai",
    "re_zhanghe",
  ],
}

const characterSortTranslate = {
  refresh_standard: "界限突破·标",
  refresh_feng: "界限突破·风",
  refresh_huo: "界限突破·火",
  refresh_lin: "界限突破·林",
  refresh_shan: "界限突破·山",
}

export { characterSort, characterSortTranslate }
