export default {
  "#botu1": "今日起兵，渡江攻敌！",
  "#botu2": "时机已到，全军出击！",

  "#olyaowu1": "这些杂兵，我有何惧！",
  "#olyaowu2": "有吾在此，解太师烦忧。",
  "#shizhan1": "兀那汉子，且报上名来！",
  "#shizhan2": "看你能坚持几个回合！",
  "#ol_huaxiong:die": "我掉以轻心了……",

  "#reshensu_ol_xiahouyuan1": "奔轶绝尘，不留踪影。",
  "#reshensu_ol_xiahouyuan2": "健步如飞，破敌不备。",
  "#shebian1": "设变力战，虏敌千万。",
  "#shebian2": "随机应变，临机设变。",
  "#ol_xiahouyuan:die": "我的速度，还是不够……",

  "#olliegong1": "龙骨成镞，矢破苍穹。",
  "#olliegong2": "凤翎为羽，箭没坚城。",
  "#ol_huangzhong:die": "末将有负主公重托……",

  "#rekuanggu_ol_weiyan1": "只有战场，能让我感到兴奋。",
  "#rekuanggu_ol_weiyan2": "反骨狂傲，彰显本色！",
  "#reqimou1": "勇战不如奇谋。",
  "#reqimou2": "为了胜利，可以出其不意。",
  "#ol_weiyan:die": "奸贼害我……",

  "#oltianxiang1": "你岂会懂我的美丽？",
  "#oltianxiang2": "碧玉闺秀，只可远观。",
  "#rehongyan1": "我的容貌，让你心动了吗？",
  "#rehongyan2": "红颜娇花好，折花门前盼。",
  "#piaoling1": "清风拂君，落花飘零。",
  "#piaoling2": "花自飘零水自流。",
  "#ol_xiaoqiao:die": "同心而离居，忧伤以终老。",

  "#olleiji1": "疾雷迅电，不可趋避！",
  "#olleiji2": "雷霆之诛，灭军毁城！",
  "#reguidao1": "鬼道运行，由我把控！",
  "#reguidao2": "汝之命运，吾来改之！",
  "#rehuangtian1": "黄天法力，万军可灭！",
  "#rehuangtian2": "天书庇佑，黄巾可兴！",
  "#ol_zhangjiao:die": "天书无效，人心难聚……",

  "#olguhuo1": "这牌，猜对了吗？",
  "#olguhuo2": "真真假假，虚实难测。",
  "#rechanyuan1": "此咒甚重，怨念缠身。",
  "#rechanyuan2": "不信吾法，无福之缘。",
  "#ol_yuji:die": "符水失效，此病难医……",

  "#olqiangxi1": "典韦来也，谁敢一战！",
  "#olqiangxi2": "双戟青罡，百死无生。",
  "#ninge1": "古之恶来，今之典韦。",
  "#ninge2": "宁为刀俎，不为鱼肉。",
  "#ol_dianwei:die": "为将者，怎可徒手而亡？",

  "#quhu_ol_xunyu1": "两虎相斗，旁观成败。",
  "#quhu_ol_xunyu2": "驱兽相争，坐收渔利。",
  "#oljieming1": "含气在胸，有进无退。",
  "#oljieming2": "蕴节于形，生死无惧。",
  "#ol_xunyu:die": "一招不慎，为虎所噬……",

  "#bazhen_ol_sp_zhugeliang1": "八阵连心，日月同辉。",
  "#bazhen_ol_sp_zhugeliang2": "此阵变化，岂是汝等可解？",
  "#olhuoji1": "东风，让这火烧得再猛烈些吧！",
  "#olhuoji2": "赤壁借东风，燃火灭魏军。",
  "#olkanpo1": "此计奥妙，我已看破。",
  "#olkanpo2": "还有什么是我看不破的？",
  "#cangzhuo1": "藏巧于拙，用晦而明。",
  "#cangzhuo2": "寓清于浊，以屈为伸。",
  "#ol_sp_zhugeliang:die": "星途半废，夙愿未完。",

  "#ollianhuan1": "连环之策，攻敌之计。",
  "#ollianhuan2": "锁链连舟，困步难行。",
  "#olniepan1": "烈火脱胎，涅槃重生。",
  "#olniepan2": "破而后立，方有大成。",
  "#bazhen_ol_pangtong1": "八卦四象，阴阳运转。",
  "#bazhen_ol_pangtong2": "离火艮山，皆随我用。",
  "#olhuoji_ol_pangtong1": "火计诱敌，江水助势。",
  "#olhuoji_ol_pangtong2": "火烧赤壁，曹贼必败。",
  "#olkanpo_ol_pangtong1": "卧龙之才，吾也略懂。",
  "#olkanpo_ol_pangtong2": "这些小伎俩，逃不出我的眼睛！",
  "#ol_pangtong:die": "骥飞羽落，坡道归尘。",

  "#retianyi1": "天降大任，速战解围！",
  "#retianyi2": "义不从之，天必不佑！",
  "#hanzhan1": "伯符，且与我一战！",
  "#hanzhan2": "与君酣战，快哉快哉！",
  "#ol_taishici:die": "无妄之灾，难以避免……",

  "#rejianchu1": "你这身躯，怎么能快过我？",
  "#rejianchu2": "这些怎么能挡住我的威力！",
  "#ol_pangde:die": "人亡马倒，命之所归。",
}
