export default {
  yuejin: "奋强突固",
  lidian: "深明大义",
  sp_caiwenji: "金璧之才",
  caoang: "取义成仁",
  simalang: "再世神农",
  guanyinping: "武姬",
  sp_sunshangxiang: "SP孙尚香",
  dongyun: "骨鲠良相",
  sunqian: "折冲樽俎",
  dingfeng: "清侧重臣",
  zhugejin: "联盟的维系者",
  zhugeke: "兴家赤族",
  sp_pangtong: "南州士冠",
  yanjun: "志存补益",
  hetaihou: "弄权之蛇蝎",
  liuxie: "受困天子",
  sp_huangyueying: "闺中璞玉",
  tadun: "北狄王",
  liuyao: "宗英外镇",

  maliang: "白眉智士",

  sp_jiangwei: "幼麒",
  ol_zhangchunhua: "冷血皇后",
  ol_xuelingyun: "红烛垂泪",
  wolongfengchu: "一匡天下",

  // le_diaochan: "欲界非天",
  // le_dianwei: "襢裼暴虎",
  // le_jiaxu: "文和乱武",
  // le_huangyueying: "卧龙的点睛人",
}
