export default {
  "#xiaoguo1": "三军听我号令，不得撤退！",
  "#xiaoguo2": "看我先登城头，立下首功！",
  "#yuejin:die": "箭疮发作，吾命休矣。",

  "#xunxun1": "众将死战，非吾之功。",
  "#xunxun2": "爱兵如子，胜乃可全。",
  "#wangxi1": "大丈夫，何拘小节。",
  "#wangxi2": "前尘往事，莫再提起。",
  "#lidian:die": "报国杀敌，虽死犹荣……",

  "#chenqing1": "陈生死离别之苦，悲乱世之跌宕。",
  "#chenqing2": "乱世陈情，字字血泪！",
  "#mozhi1": "今日默书，方恨千卷诗书未能全记。",
  "#mozhi2": "博闻强识，不辱才女之名。",
  "#sp_caiwenji:die": "命运……弄人……",

  "#kangkai1": "典将军，比比看谁杀敌更多！",
  "#kangkai2": "父亲快走，有我殿后!",
  "#caoang:die": "典将军，还是你赢了……",

  "#junbing1": "郡国当有搜狩习战之备。",
  "#junbing2": "男儿慷慨，军中豪迈。",
  "#quji1": "愿为将士，略尽绵薄。",
  "#quji2": "若不去兵之疾，则将何以守国？",
  "#simalang:die": "微功未效，有辱国恩。",

  "#xueji1": "这炽热的鲜血，父亲，你可感觉得到？",
  "#xueji2": "取你首级，祭先父之灵！",
  "#huxiao1": "大仇未报，还不能放弃。",
  "#huxiao2": "虎父无犬女！",
  "#wuji1": "我感受到了，父亲的力量。",
  "#wuji2": "我也要像父亲那样坚强。",
  "#guanyinping:die": "父亲，你来救我了吗？",

  "#liangzhu1": "两国结盟，你我都是一家人。",
  "#liangzhu2": "吾愿携弩，征战沙场，助君一战！",
  "#fanxiang1": "今夕一别，不知何日再见。",
  "#fanxiang2": "兄命难违，从此两别。",
  "#xiaoji_sp_sunshangxiang1": "双剑夸巧，不让须眉！",
  "#xiaoji_sp_sunshangxiang2": "弓马何须忌红妆？",
  "#sp_sunshangxiang:die": "东途难归，初心难追。",

  "#bingzheng1": "自古，就是邪不胜正！",
  "#bingzheng2": "主公面前，岂容小人搬弄是非！",
  "#sheyan1": "还是改日吧。",
  "#sheyan2": "公事繁忙，宴席不去也罢。",
  "#dongyun:die": "大汉，要亡于宦官之手了。",

  "#qianya1": "哎！将军过誉了！",
  "#qianya2": "君子不妄动，动必有道。",
  "#shuimeng1": "你我唇齿相依，共御外敌，何如？",
  "#shuimeng2": "今兵薄势寡，可遣某为使往说之。",
  "#sunqian:die": "恨不能得见皇叔早登大宝，咳咳咳……",

  "#duanbing1": "短兵轻甲，也可取汝性命！",
  "#duanbing2": "众将官，短刀出鞘。",
  "#fenxun1": "取封侯爵赏，正在今日。",
  "#fenxun2": "给我拉过来！",
  "#dingfeng:die": "这风，太冷了……",

  "#huanshi1": "缓乐之危急，释兵之困顿。",
  "#huanshi2": "尽死生之力，保友邦之安。",
  "#hongyuan1": "诸将莫慌，粮草已到。",
  "#hongyuan2": "自舍其身，施于天下。",
  "#mingzhe1": "塞翁失马，焉知非福。",
  "#mingzhe2": "明以洞察，哲以保身。",
  "#zhugejin:die": "君臣不相负，来世复君臣。",

  "#aocai1": "哼，易如反掌。",
  "#aocai2": "吾主圣明，泽被臣属。",
  "#duwu1": "全力攻城，言退者斩！",
  "#duwu2": "破曹大功，正在今朝！",
  "#zhugeke:die": "重权震主，是我疏忽了。",

  "#guolun1": "品过是非，讨评好坏。",
  "#guolun2": "若有天下太平时，必讨四海之内才。",
  "#songsang1": "送丧至东吴，使命已完。",
  "#songsang2": "送丧虽至，吾与孝则得相交。",
  "#zhanji1": "功曹之恩，吾必有展骥之机。",
  "#zhanji2": "公瑾安全至吴，心安之。",
  "#sp_pangtong:die": "我终究……不得东吴赏识。",

  "#guanchao1": "朝夕之间，可知所进退。",
  "#guanchao2": "月盈，潮起晨暮也；月亏，潮起日半也。",
  "#xunxian1": "督军之才，子明强于我甚多。",
  "#xunxian2": "此间重任，公卿可担之。",
  "#yanjun:die": "著作……还没完成……",

  "#zhendu1": "怪只怪你，不该生有皇子！",
  "#zhendu2": "后宫之中，岂有你的位置！",
  "#qiluan1": "待我召吾兄入宫，谁敢不从？",
  "#qiluan2": "本后自由哥哥在外照应，有什么好担心的！",
  "#hetaihou:die": "你们男人造的孽，非要说什么红颜祸水……",

  "#tianming1": "朕乃大汉皇帝，天命之子！",
  "#tianming2": "皇汉国祚，千年不息！",
  "#mizhao1": "爱卿世受皇恩，堪此重任。",
  "#mizhao2": "此诏事关重大，切记小心行事。",
  "#liuxie:die": "为什么，不把复兴汉室的权力交给我……",

  "#jiqiao1": "驭巧器，以取先机。",
  "#jiqiao2": "颖悟之人，不以拙力取胜。",
  "#linglong1": "哼，书中自有玲珑心。",
  "#linglong2": "哼，自然是多多益善咯。",
  "#sp_huangyueying:die": "只恨不能再助夫君了。",

  "#luanzhan1": "受袁氏大恩，当效死力。",
  "#luanzhan2": "现，正是我乌桓崛起之机。",
  "#tadun:die": "呃，不该，趟曹袁之争的浑水……",

  "#kannan1": "俊才之杰，材匪戡难。",
  "#kannan2": "戡，克也，难，攻之。",
  "#liuyao:die": "伯符小儿，还我子义！",

  "#zishu1": "慢着，让我来！",
  "#zishu2": "身外之物，不要也罢！",
  "#yingyuan1": "好牌只用一次怎么够？",
  "#yingyuan2": "接好嘞！",
  "#maliang:die": "我的使命完成了吗……",

  "#kunfen1": "纵使困顿难行，亦当砥砺奋进！",
  "#kunfen2": "兴蜀需时，众将且勿惫怠！",
  "#fengliang1": "丞相大义，维岂有不从之理？",
  "#fengliang2": "得遇丞相，再生之德。",
  "#tiaoxin_sp_jiangwei1": "今日天公作美，怎能不战而退？",
  "#tiaoxin_sp_jiangwei2": "贼将无胆，何不早降！",
  "#sp_jiangwei:die": "伯约已尽力而为，奈何大汉，国运衰微……",

  "#jueqing_ol_zhangchunhua1": "情丝如雪，难当暖阳。",
  "#jueqing_ol_zhangchunhua2": "有情总被无情负，绝情方无软肋生。",
  "#shangshi_ol_zhangchunhua1": "伤我最深的，竟是你司马懿。",
  "#shangshi_ol_zhangchunhua2": "世间刀剑数万，何以情字伤人？",
  "#jianmie1": "莫说是你，天潢贵胄亦可杀得！",
  "#jianmie2": "你我不到黄泉，不复相见！",
  "#ol_zhangchunhua:die": "我不负懿，懿负我。",

  "#siqi1": "红泪落霜鬓，自此无处归乡。",
  "#siqi2": "挥泪别古道，唯见瘦马曳西风。",
  "#qiaozhi1": "皓齿断银丝，轻吻公子衣上雪。",
  "#qiaozhi2": "玉指拈锦线，今日织君身上衣。",
  "#ol_xuelingyun:die": "宫墙阻春柳，此心藏玉壶。",

  "#youlong1": "赤壁献策，再谱春秋！",
  "#youlong2": "卧龙出山，谋定万古！",
  "#luanfeng1": "凤栖枯木，浴火涅槃！",
  "#luanfeng2": "青鸾归羽，雏凤还巢！",
  "#wolongfengchu:die": "铁链，东风，也难困这魏军……",
}
