export default {
  "#kunfen1": "纵使困顿难行，亦当砥砺奋进！",
  "#kunfen2": "兴蜀需时，众将且勿惫怠！",
  "#fengliang1": "丞相大义，维岂有不从之理？",
  "#fengliang2": "得遇丞相，再生之德。",
  "#tiaoxin_sp_jiangwei1": "今日天公作美，怎能不战而退？",
  "#tiaoxin_sp_jiangwei2": "贼将无胆，何不早降！",
  "#sp_jiangwei:die": "伯约已尽力而为，奈何大汉，国运衰微……",

  "#jueqing_ol_zhangchunhua1": "情丝如雪，难当暖阳。",
  "#jueqing_ol_zhangchunhua2": "有情总被无情负，绝情方无软肋生。",
  "#shangshi_ol_zhangchunhua1": "伤我最深的，竟是你司马懿。",
  "#shangshi_ol_zhangchunhua2": "世间刀剑数万，何以情字伤人？",
  "#jianmie1": "莫说是你，天潢贵胄亦可杀得！",
  "#jianmie2": "你我不到黄泉，不复相见！",
  "#ol_zhangchunhua:die": "我不负懿，懿负我。",

  "#siqi1": "红泪落霜鬓，自此无处归乡。",
  "#siqi2": "挥泪别古道，唯见瘦马曳西风。",
  "#qiaozhi1": "皓齿断银丝，轻吻公子衣上雪。",
  "#qiaozhi2": "玉指拈锦线，今日织君身上衣。",
  "#ol_xuelingyun:die": "宫墙阻春柳，此心藏玉壶。",

  "#youlong1": "赤壁献策，再谱春秋！",
  "#youlong2": "卧龙出山，谋定万古！",
  "#luanfeng1": "凤栖枯木，浴火涅槃！",
  "#luanfeng2": "青鸾归羽，雏凤还巢！",
  "#wolongfengchu:die": "铁链，东风，也难困这魏军……",

  "#yingyuan1": "接好嘞！",
  "#yingyuan2": "好牌只用一次怎么够？",
  "#zishu1": "慢着，让我来！",
  "#zishu2": "身外之物，不要也罢！",
  "#maliang:die": "我的使命……完成了吗……",
}
