const characters = {
  caozhi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["luoying", "jiushi"],
  },
  yujin: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["zhenjun"],
  },
  zhangchunhua: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["jueqing", "shangshi"],
  },
  fazheng: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["enyuan", "xuanhuo"],
  },
  masu: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["sanyao", "zhiman"],
  },
  xushu: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["wuyan", "jujian"],
    groupBorder: "wei",
  },
  lingtong: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["xuanfeng"],
  },
  wuguotai: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["ganlu", "buyi"],
    names: "丁|null",
  },
  xusheng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["pojun"],
  },
  chengong: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["mingce", "zhichi"],
  },
  gaoshun: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["xianzhen", "jinjiu"],
  },

  zhonghui: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["quanji", "zili"],
    clans: ["颍川钟氏"],
  },
  wangyi: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["zhenlie", "miji"],
  },
  xunyou: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["qice", "zhiyu"],
    clans: ["颍川荀氏"],
  },
  guanzhang: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["fuhun"],
    names: "关|兴-张|苞",
  },
  liaohua: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["dangxian", "fuli"],
  },
  madai: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "qianxi"],
  },
  bulianshi: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["anxu", "zhuiyi"],
  },
  chengpu: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["lihuo", "chunlao"],
  },
  handang: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["gongqi", "jiefan"],
  },
  liubiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["zishou", "zongshi"],
  },

  caochong: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["chengxiang", "renxin"],
  },
  guohuai: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jingce"],
  },
  manchong: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["junxing", "yuce"],
  },
  guanping: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["longyin"],
  },
  jianyong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["qiaoshui", "jyzongshi"],
  },
  liufeng: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["xiansi"],
  },
  panzhangmazhong: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["duodao", "anjian"],
    names: "潘|璋-马|忠",
  },
  yufan: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["zongxuan", "zhiyan"],
  },
  zhuran: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["danshou"],
  },
  fuhuanghou: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["zhuikong", "qiuyuan"],
  },
  liru: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["juece", "mieji", "fencheng"],
    dieAudios: ["liru"],
  },

  caozhen: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["sidi"],
  },
  chenqun: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["pindi", "faen"],
    clans: ["颍川陈氏"],
  },
  hanhaoshihuan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["shenduan", "yonglve"],
    names: "韩|浩-史|涣",
  },
  wuyi: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["benxi"],
    clans: ["陈留吴氏"],
  },
  zhangsong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["qiangzhi", "xiantu"],
  },
  zhoucang: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["zhongyong"],
  },
  guyong: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["shenxing", "bingyi"],
  },
  sunluban: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["chanhui", "jiaojin"],
  },
  zhuhuan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["fenli", "pingkou"],
  },
  caifuren: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["qieting", "xianzhou"],
    names: "蔡|null",
  },
  yj_jushou: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jianying", "shibei"],
  },

  caorui: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["huituo", "mingjian", "xingshuai"],
    isZhugong: true,
  },
  caoxiu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["qianju", "qingxi"],
  },
  zhongyao: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["huomo", "zuoding"],
    clans: ["颍川钟氏"],
  },
  liuchen: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["zhanjue", "qinwang"],
    isZhugong: true,
  },
  xiahoushi: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["qiaoshi", "yanyu"],
    names: "夏侯|null",
  },
  zhangyi: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["wurong", "shizhi"],
  },
  quancong: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["yaoming"],
  },
  sunxiu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["yanzhu", "xingxue", "zhaofu"],
    isZhugong: true,
  },
  zhuzhi: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["anguo"],
  },
  gongsunyuan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["huaiyi"],
    names: "公孙|渊",
  },
  guotufengji: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jigong", "shifei"],
    names: "郭|图-逢|纪",
  },

  qinmi: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["jianzheng", "zhuandui", "tianbian"],
  },
}

export default characters
