export default {
  caozhi: "八斗之才",
  yujin: "讨暴坚垒",
  zhangchunhua: "冷血皇后",
  fazheng: "蜀汉的辅翼",
  masu: "军略之才器",
  xushu: "忠孝的侠士",
  lingtong: "豪情烈胆",
  wuguotai: "武烈皇后",
  xusheng: "江东的铁壁",
  chengong: "刚直壮烈",
  gaoshun: "攻无不克",

  zhonghui: "桀骜的野心家",
  wangyi: "决意的巾帼",
  xunyou: "曹魏的谋主",
  guanzhang: "将门虎子",
  liaohua: "历尽沧桑",
  madai: "临危受命",
  bulianshi: "无冕之后",
  chengpu: "三朝虎臣",
  handang: "石城侯",
  liubiao: "跨蹈汉南",

  caochong: "仁爱的神童",
  guohuai: "垂问秦雍",
  manchong: "政法兵谋",
  guanping: "忠臣孝子",
  jianyong: "优游风议",
  liufeng: "骑虎之殇",
  panzhangmazhong: "擒龙伏虎",
  yufan: "狂直之士",
  zhuran: "不动之督",
  fuhuanghou: "孤注一掷",
  liru: "魔仕",

  caozhen: "荷国天督",
  chenqun: "万世臣表",
  hanhaoshihuan: "中军之主",
  wuyi: "建兴鞍辔",
  zhangsong: "怀璧待凤仪",
  zhoucang: "披肝沥胆",
  guyong: "庙堂的玉磬",
  sunluban: "为虎作伥",
  zhuhuan: "中洲拒天人",
  caifuren: "襄江的蒲苇",
  yj_jushou: "监军谋国",

  caorui: "天姿的明君",
  caoxiu: "千里骐骥",
  zhongyao: "正楷萧曹",
  liuchen: "血荐轩辕",
  xiahoushi: "采缘撷睦",
  zhangyi: "通壮逾古",
  quancong: "慕势耀族",
  sunxiu: "弥殇的景君",
  zhuzhi: "王事靡盬",
  gongsunyuan: "狡徒悬海",
  guotufengji: "凶蛇两端",

  qinmi: "彻天之舌",
}
