const characters = {
  caozhi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["luoying", "jiushi"],
  },
  yujin: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["zhenjun"],
  },
  zhangchunhua: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["jueqing", "shangshi"],
  },
  fazheng: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["enyuan", "xuanhuo"],
  },
  masu: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["sanyao", "zhiman"],
  },
  xushu: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["wuyan", "jujian"],
    groupBorder: "wei",
  },
  lingtong: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["xuanfeng"],
  },
  wuguotai: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["ganlu", "buyi"],
    names: "丁|null",
  },
  xusheng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["pojun"],
  },
  chengong: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["mingce", "zhichi"],
  },
  gaoshun: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["xianzhen", "jinjiu"],
  },

  zhonghui: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["quanji", "zili"],
    clans: ["颍川钟氏"],
  },
  wangyi: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["zhenlie", "miji"],
  },
  xunyou: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["qice", "zhiyu"],
    clans: ["颍川荀氏"],
  },
  guanzhang: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["fuhun"],
    names: "关|兴-张|苞",
  },
  liaohua: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["dangxian", "fuli"],
  },
  madai: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "qianxi"],
  },
  bulianshi: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["anxu", "zhuiyi"],
  },
  chengpu: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["lihuo", "chunlao"],
  },
  handang: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["gongqi", "jiefan"],
  },
  liubiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["zishou", "zongshi"],
  },

  caochong: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["chengxiang", "renxin"],
  },
  guohuai: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jingce"],
  },
  manchong: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["junxing", "yuce"],
  },
  guanping: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["longyin"],
  },
  jianyong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["qiaoshui", "jyzongshi"],
  },
  liufeng: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["xiansi"],
  },
  panzhangmazhong: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["duodao", "anjian"],
    names: "潘|璋-马|忠",
  },
  yufan: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["zongxuan", "zhiyan"],
  },
  zhuran: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["danshou"],
  },
  fuhuanghou: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["zhuikong", "qiuyuan"],
  },
  liru: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["juece", "mieji", "fencheng"],
    dieAudios: ["liru"],
  },

  qinmi: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["jianzheng", "zhuandui", "tianbian"],
  },
}

export default characters
