const characterSort = {
  yijiang_2011: [
    "caozhi",
    "yujin",
    "zhangchunhua",
    "xin_fazheng",
    "xin_masu",
    "xin_xushu",
    "xusheng",
    "lingtong",
    "wuguotai",
    "chengong",
    "gaoshun",
  ],
  yijiang_2012: [
    "wangyi",
    "xunyou",
    "zhonghui",
    "old_madai",
    "liaohua",
    "guanzhang",
    "bulianshi",
    "handang",
    "chengpu",
    "liubiao",
    "old_huaxiong",
    "caozhang",
  ],
  yijiang_2013: [
    "manchong",
    "guohuai",
    "caochong",
    "guanping",
    "liufeng",
    "jianyong",
    "yufan",
    "panzhangmazhong",
    "zhuran",
    "xin_liru",
    "fuhuanghou",
  ],
  yijiang_2014: [
    "hanhaoshihuan",
    "chenqun",
    "caozhen",
    "zhangsong",
    "wuyi",
    "zhoucang",
    "zhuhuan",
    "guyong",
    "sunluban",
    "yj_jushou",
    "caifuren",
  ],
  yijiang_2015: [
    "caoxiu",
    "caorui",
    "zhongyao",
    "xiahoushi",
    "liuchen",
    "zhangyi",
    "zhuzhi",
    "quancong",
    "sunxiu",
    "gongsunyuan",
    "guotufengji",
  ],
  yijiang_2022: [
    "guohuanghou",
    "sunziliufang",
    "huanghao",
    "liyan",
    "sundeng",
    "cenhun",
    "zhangrang",
    "liuyu",
  ],
  yijiang_2023: [
    "xinxianying",
    "jikang",
    "wuxian",
    "qinmi",
    "xuezong",
    "xushi",
    "caiyong",
    "caojie",
  ],
  yijiang_doukou: [
    "re_xinxianying",
    "xuelingyun",
    "duanqiaoxiao",
    "tianshangyi",
    "bailingyun",
    "huaman",
    "zhugeguo",
    "dc_ruiji",
    "re_tianshangyi",
  ],
}

const characterSortTranslate = {
  yijiang_2011: "一将成名2011",
  yijiang_2012: "一将成名2012",
  yijiang_2013: "一将成名2013",
  yijiang_2014: "一将成名2014",
  yijiang_2015: "一将成名2015",
  yijiang_doukou: "一将成名·豆蔻梢头",
  yijiang_zhengyin: "一将成名·正音雅乐",
  yijiang_jinse: "一将成名·锦瑟良缘",
  yijiang_caizijiaren: "一将成名·才子佳人",
}

export { characterSort, characterSortTranslate }
