export default {
  "#rezhongjian1": "管中可窥豹，一叶而知秋。",
  "#rezhongjian2": "此人肆意放纵，必有异志！",
  "#recaishi1": "小女才疏学浅，将军见笑了。",
  "#recaishi2": "谁说女子无才便是德？",
  "#re_xinxianying:die": "看错你，竟是万劫不复！",

  "#xialei1": "采霞揾晶泪，沾我青衫湿。",
  "#xialei2": "登车入宫墙，垂泪凝如瑙。",
  "#anzhi1": "深闱行彩线，唯手熟尔。",
  "#anzhi2": "星月独照人，何谓之暗？",
  "#xuelingyun:die": "寒月隐幕，难作衣裳。",

  "#posuo1": "绯纱婆娑起，佳人笑靥红。",
  "#posuo2": "红烛映俏影，一舞影斑斓。",
  "#xiaoren1": "红绡举腕重，明眸最溺人。",
  "#xiaoren2": "飘然回雪轻，言然游龙惊。",
  "#tianshangyi:die": "红梅待百花，魏宫无春风。",

  "#manyi1": "南蛮女子，该当英勇善战！",
  "#manyi2": "蛮族的力量，你可不要小瞧！",
  "#mansi1": "承父母庇护，得此服气。",
  "#mansi2": "多谢父母怜爱。",
  "#souying1": "幽薮影单，只身勇斗！",
  "#souying2": "真薮影移，险战不惧！",
  "#zhanyuan1": "战中结缘，虽苦亦甜。",
  "#zhanyuan2": "势不同，情相随。",
  "#xili1": "系力而为，助君得胜。",
  "#xili2": "有我在，将军此战必能一举拿下！",
  "#huaman:die": "南蛮之地的花，还在开吗……",

  "#qirang1": "集母亲之智，效父亲之法，祈以七星。",
  "#qirang2": "仙甲既来，岂无仙术乎。",
  "#yuhua1": "凤羽飞烟，乘化仙尘。",
  "#yuhua2": "此乃仙人之物，不可轻弃。",
  "#zhugeguo:die": "方生方死，方死方生。",

  "#wangyuan1": "小女子不才，愿伴公子余生。",
  "#wangyuan2": "纵有万钧之力，然不斩情丝。",
  "#lingyin1": "环佩莞尔，心动情动、铃儿动。",
  "#lingyin2": "小鹿撞入我怀，银铃焉能不鸣？",
  "#liying1": "飞影掠白鹭，日暮栖君怀。",
  "#liying2": "妾影婆娑，摇曳君心。",
  "#dc_ruiji:die": "佳人芳华逝，空余孤铃鸣。",

  "#posuo_re_tianshangyi1": "垂带飞旋转红袖，满头钗翠摇，香风回白马。",
  "#posuo_re_tianshangyi2": "紫鬓遏云响春风，娇娘舞腰轻，挽指作倾城。",
  "#xiaoren_re_tianshangyi1": "落花绕树疑无影，红绡从风暗有情。",
  "#xiaoren_re_tianshangyi2": "舞衣无力清风敛，飞旋秋色潋珠光。",
  "#re_tianshangyi:die": "陛下三千粉黛，妾已泯为其中。",
}
