const characters = {
  caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jianxiong", "hujia"],
    isZhugong: true,
  },
  simayi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["fankui", "guicai"],
    names: "司马|懿",
  },
  xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["ganglie"],
    names: "夏侯|惇",
  },
  zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["tuxi"],
  },
  xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["luoyi"],
  },
  guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "yiji"],
  },
  zhenji: {
    sex: "female",
    group: "wei",
    hp: 3,
    skills: ["luoshen", "qingguo"],
  },
  liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["rende", "jijiang"],
    isZhugong: true,
  },
  guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["wusheng"],
  },
  zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["paoxiao"],
  },
  zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["guanxing", "kongcheng"],
    names: "诸葛|亮",
  },
  zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["longdan"],
  },
  machao: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["mashu", "tieji"],
  },
  huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["jizhi", "qicai"],
  },
  sunquan: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["zhiheng", "jiuyuan"],
    isZhugong: true,
  },
  ganning: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["qixi"],
  },
  lvmeng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["keji"],
  },
  huanggai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["kurou"],
  },
  zhouyu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["yingzi", "fanjian"],
  },
  daqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["guose", "liuli"],
    names: "桥|null",
  },
  luxun: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["qianxun", "lianying"],
    clans: ["吴郡陆氏"],
  },
  sunshangxiang: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["jieyin", "xiaoji"],
  },
  huatuo: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["jijiu", "qingnang"],
  },
  lvbu: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["wushuang"],
  },

  diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["lijian", "biyue"],
    names: "null|null",
  },
  huaxiong: {
    sex: "male",
    group: "qun",
    hp: 6,
    skills: ["yaowu"],
  },

  gongsunzan: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["yicong"],
    names: "公孙|瓒",
  },

  std_yuejin: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["stdxiaoguo"],
    dieAudios: ["yuejin"],
  },
  ganfuren: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["shenzhi", "shushen"],
    names: "甘|null",
  },
  std_panfeng: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["stdkuangfu"],
    dieAudios: ["panfeng"],
  },

  kongrong: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["cirang", "liaoliao"],
  },
}

export default characters
