const characters = {
  old_diaochan: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["relijian", "biyue"],
    names: "null|null",
  },
  old_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["oldrende", "jijiang"],
    isZhugong: true,
    img: "image/character/re_liubei.jpg",
    dieAudios: ["re_liubei"],
  },
  old_huangyueying: {
    sex: "female",
    group: "shu",
    hp: 3,
    skills: ["oldjizhi", "oldqicai"],
    img: "image/character/re_huangyueying.jpg",
    dieAudios: ["re_huangyueying"],
  },
  old_yuanshu: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["wangzun", "tongji"],
  },
  old_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["wusheng", "oldyijue"],
    img: "image/character/re_guanyu.jpg",
    dieAudios: ["re_guanyu"],
  },
  old_zhangfei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["paoxiao", "oldtishen"],
    img: "image/character/re_zhangfei.jpg",
    dieAudios: ["re_zhangfei"],
  },
  old_zhaoyun: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["longdan", "oldyajiao"],
    img: "image/character/re_zhaoyun.jpg",
    dieAudios: ["re_zhaoyun"],
  },
  re_xushu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["zhuhai", "qianxin"],
  },
  old_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldjianxiong", "hujia"],
    isZhugong: true,
    img: "image/character/re_caocao.jpg",
    dieAudios: ["re_caocao"],
  },
  old_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reganglie", "oldqingjian"],
    names: "夏侯|惇",
    img: "image/character/re_xiahoudun.jpg",
    dieAudios: ["re_xiahoudun"],
  },
  old_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldtuxi"],
    img: "image/character/re_zhangliao.jpg",
    dieAudios: ["re_zhangliao"],
  },
  old_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldluoyi"],
    img: "image/character/re_xuzhu.jpg",
    dieAudios: ["re_xuzhu"],
  },
  old_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "oldyiji"],
    img: "image/character/re_guojia.jpg",
    dieAudios: ["re_guojia"],
  },
  old_lvbu: {
    sex: "male",
    group: "qun",
    hp: 5,
    skills: ["wushuang", "oldliyu"],
    img: "image/character/re_lvbu.jpg",
    dieAudios: ["re_lvbu"],
  },

  old_yujin: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["yizhong"],
  },
  old_fazheng: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["oldenyuan", "oldxuanhuo"],
  },
  old_masu: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["xinzhan", "huilei"],
    dieAudios: ["masu"],
  },
  old_xushu: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["oldwuyan", "oldjujian"],
    groupBorder: "wei",
  },
  old_lingtong: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["oldxuanfeng"],
    dieAudios: ["lingtong"],
  },
  old_xusheng: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["oldpojun"],
    img: "image/character/dc_xusheng.jpg",
    dieAudios: ["xusheng"],
  },
}

export default characters
