const characters = {
  old_caocao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldjianxiong", "hujia"],
    isZhugong: true,
    img: "image/character/re_caocao.jpg",
    dieAudios: ["re_caocao"],
  },
  old_xiahoudun: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["reganglie", "oldqingjian"],
    names: "夏侯|惇",
    img: "image/character/re_xiahoudun.jpg",
    dieAudios: ["re_xiahoudun"],
  },
  old_zhangliao: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldtuxi"],
    img: "image/character/re_zhangliao.jpg",
    dieAudios: ["re_zhangliao"],
  },
  old_xuzhu: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["oldluoyi"],
    img: "image/character/re_xuzhu.jpg",
    dieAudios: ["re_xuzhu"],
  },
  old_guojia: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["tiandu", "oldyiji"],
    img: "image/character/re_guojia.jpg",
    dieAudios: ["re_guojia"],
  },
  lidian: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["xunxun", "wangxi"],
  },
  old_liubei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["oldrende", "jijiang"],
    isZhugong: true,
    img: "image/character/re_liubei.jpg",
    dieAudios: ["re_liubei"],
  },
  old_guanyu: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["wusheng", "oldyijue"],
    img: "image/character/re_guanyu.jpg",
    dieAudios: ["re_guanyu"],
  },
}

export default characters
