window.wtk_package = {
  character: {
    //经典标包＋神话再临
    standard: "标准版",
    shenhua: "神话再临",
    refresh: "界限突破",
    jieshenhua: "界神话再临",
    jiangxing: "将星",
    zhencang: "珍藏版",
    // shenwu: "神武再世",
    tianshui: "天水濯名",
    jsrg: "江山如故",
    sxrm: "蚀心入魔",
    yanling: "雁翎耀光",
  },
  card: {
    standard: "标准版",
    extra: "军争篇",
    refresh: "界限突破",
    wangzhe: "王者之战",
    simplified: "精简版",
    yongjian: "用间篇",
    zhulu: "逐鹿天下",
    seal: "珍藏封印",
  },
  play: {
    boss: "诸神降临",
    cardpile: "牌堆补充",
    coin: "富甲天下",
  },
  mode: {
    identity: "身份",
    guozhan: "国战",
    versus: "对决",
    connect: "联机",
    boss: "挑战",
    doudizhu: "斗地主",
    single: "单挑",
    chess: "战棋",
    tafang: "塔防",
    stone: "炉石",
    brawl: "乱斗",
  },
  submode: {
    identity: {
      normal: "身份模式",
      zhong: "忠胆英杰",
      purple: "3v3v2",
    },
    guozhan: {
      normal: "国战模式",
      mingjiang: "明将国战",
    },
    versus: {
      four: "四人对抗",
      three: "统率三军",
      two: "欢乐成双",
      jiange: "守卫剑阁",
      siguo: "四国争霸",
      standard: "自由对决",
    },
    chess: {
      combat: "战棋模式",
      three: "战棋统率",
      leader: "战棋君主",
    },
    single: {
      normal: "新1v1",
    },
  },
  background: {
    ol_bg: "龙纹",
    planetarian_bg: "星梦",
    heaven_bg: "红烧",
    kyoani_bg: "京都",
    key_bg: "键社",
    xiaowu_bg: "小无",
    wtk_bg: "璀璨",
    wuming_bg: "无名",
    zhulin_bg: "竹林",
    shengshi_bg: "盛世",
    taoyuan_bg: "桃园",
    zhanhuo_bg: "战火",
    huangtian_bg: "黄天",
    september_bg: "九月",
    yinxiang_bg: "印象",
    zhanyun_bg: "战云",
    beipan_bg: "背叛",
    lanting_bg: "兰亭",
    lingju_bg: "灵雎",
    sanying_bg: "三英",
    wangshi_bg: "往事",
    xiongxin_bg: "雄心",
    xinsha_bg: "新杀",
  },
  music: {
    music_phliosophy: "Philosophy of ours",
    music_diaochan: "貂蝉",
    music_shezhan: "舌战群儒",
    music_danji: "千里走单骑",
    music_jifeng: "祭风",
    music_jilve: "极略",
    effect_caomaoBJM: "向死存魏",
    effect_yinzhanBGM: "势魏延饮战",
    effect_tuishouBGM: "势魏延退守",
  },
  font: {
    xiaozhuan: "方正小篆体",
    xinwei: "华文新魏_GBK",
    huangcao: "方正黄草_GBK",
    yuanli: "方正北魏楷书_GBK",
    xingkai: "方正行楷_GBK",
    shousha: "方正隶变_GBK",
  },
  theme: {
    woodden: "木纹",
    music: "音乐",
    simple: "简约",
  },
}
