window.wtk_package = {
  character: {
    standard: "标准版",
    shenhua: "神话再临",
    refresh: "界限突破",
    reshenhua: "界神话再临",
    shenwu: "神武再世",
    old: "往昔龙吟",
    // jiangxing: "将星",
    // extra: "珍藏版",
    // jsrg: "江山如故",
    // tianshui: "天水濯名",
    // sxrm: "蚀心入魔",
    // yanling: "雁翎耀光",
  },
  card: {
    standard: "标准版",
    extra: "军争篇",
    refresh: "界限突破",
    sixiang: "珍藏封印",
    sp: "忠胆英杰",
    wangzhe: "王者之战",
    yingbian: "应变篇",
    simplify: "精简版",
    yongjian: "用间篇",
    guozhan: "国战",
    zhulu: "逐鹿天下",
  },
  mode: {
    identity: "身份",
    guozhan: "国战",
    versus: "对决",
    connect: "联机",
    boss: "挑战",
    doudizhu: "斗地主",
    single: "单挑",
    brawl: "乱斗",
  },
  submode: {
    identity: {
      normal: "身份模式",
      zhong: "忠胆英杰",
      purple: "3v3v2",
    },
    guozhan: {
      normal: "国战模式",
      mingjiang: "明将国战",
    },
    versus: {
      four: "四人对抗",
      three: "统率三军",
      two: "欢乐成双",
      jiange: "守卫剑阁",
      siguo: "四国争霸",
      standard: "自由对决",
    },
    single: {
      normal: "新1v1",
    },
  },
  background: { ol_bg: "龙纹" },
  font: {
    xiaozhuan: "方正小篆体",
    xinwei: "华文新魏_GBK",
    huangcao: "方正黄草_GBK",
    yuanli: "方正北魏楷书_GBK",
    xingkai: "方正行楷_GBK",
    shousha: "方正隶变_GBK",
  },
  theme: { simple: "简约" },
}
