export default {
  yuji: "太平道人",
  zhangjiao: "天公将军",
  weiyan: "嗜血的独狼",
  huangzhong: "老当益壮",
  caoren: "大将军",
  xiahouyuan: "疾行的猎豹",
  zhoutai: "历战之躯",
  xiaoqiao: "矫情之花",
  shen_guanyu: "鬼神再临",
  shen_lvmeng: "圣光之国士",

  dianwei: "古之恶来",
  xunyu: "王佐之才",
  taishici: "笃烈之士",
  pangde: "人马一体",
  yanwen: "虎狼兄弟",
  yuanshao: "高贵的名门",
  pangtong: "凤雏",
  sp_zhugeliang: "卧龙",
  shen_zhugeliang: "赤壁的妖术师",
  shen_zhouyu: "赤壁的火神",

  lusu: "独断的外交家",
  sunjian: "武烈帝",
  dongzhuo: "魔王",
  jiaxu: "冷酷的毒士",
  menghuo: "南蛮王",
  zhurong: "野性的女王",
  caopi: "霸业的继承者",
  xuhuang: "周亚夫之风",
  shen_lvbu: "修罗之道",
  shen_caocao: "超世之英杰",

  caiwenji: "异乡的孤女",
  zuoci: "迷之仙人",
  jiangwei: "龙的衣钵",
  liushan: "无为的真命主",
  sunce: "江东的小霸王",
  // zhanghe: "料敌机先",
  // dengai: "矫然的壮士",
  // old_dengai: "武将列传",
  // zhangzhang: "经天纬地",

  // re_lusu: "独断外交家",
  // wangji: "经行合一",
  // kuailiangkuaiyue: "雍论臼谋",
  // sunliang: "寒江枯木",
  // yl_luzhi: "国之桢干",
  // xuyou: "朝秦暮楚",
  // luji: "瑚琏之器",
  // wangping: "兵谋以致用",
  // yanyan: "断头将军",
  // zhugezhan: "临难死义",
  // lukang: "社稷之瑰宝",
  // haozhao: "扣弦的豪将",
  // yl_yuanshu: "仲家帝",
  // zhangxiu: "北地枪王",
  // chendao: "白毦督",
  // re_pangde: "人马一体",
  // guanqiujian: "镌功铭征荣",
  // zhoufei: "软玉温香",
  // old_zhoufei: "战场绝版",
}
