export default {
  caoren: "大将军",
  xiahouyuan: "疾行的猎豹",
  huangzhong: "老当益壮",
  weiyan: "嗜血的独狼",
  xiaoqiao: "矫情之花",
  zhoutai: "历战之躯",
  zhangjiao: "天公将军",
  yuji: "太平道人",
  shen_guanyu: "鬼神再临",
  shen_lvmeng: "圣光之国士",

  dianwei: "古之恶来",
  xunyu: "王佐之才",
  sp_zhugeliang: "卧龙",
  pangtong: "凤雏",
  taishici: "笃烈之士",
  pangde: "人马一体",
  yuanshao: "高贵的名门",
  yanwen: "虎狼兄弟",
  shen_zhouyu: "赤壁的火神",
  shen_zhugeliang: "赤壁的妖术师",

  caopi: "霸业的继承者",
  xuhuang: "周亚夫之风",
  zhurong: "野性的女王",
  menghuo: "南蛮王",
  lusu: "独断的外交家",
  sunjian: "武烈帝",
  dongzhuo: "魔王",
  jiaxu: "冷酷的毒士",
  shen_lvbu: "修罗之道",
  shen_caocao: "超世之英杰",

  dengai: "矫然的壮士",
  zhanghe: "料敌机先",
  jiangwei: "龙的衣钵",
  liushan: "无为的真命主",
  sunce: "江东的小霸王",
  zhangzhang: "经天纬地",
  zuoci: "迷之仙人",
  caiwenji: "异乡的孤女",
  shen_simayi: "晋国之祖",
  shen_zhaoyun: "神威如龙",

  guanqiujian: "镌功铭征荣",
}
