const characters = {
  yuji: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["guhuo"],
  },
  zhangjiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["leiji", "guidao", "huangtian"],
    isZhugong: true,
  },
  weiyan: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["kuanggu"],
  },
  huangzhong: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["liegong"],
  },
  caoren: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jushou"],
  },
  xiahouyuan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["shensu"],
    names: "夏侯|渊",
  },
  zhoutai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["buqu"],
  },
  xiaoqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["tianxiang", "hongyan"],
    names: "桥|null",
  },
  shen_guanyu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["wushen", "wuhun"],
    groupInGuozhan: "shu",
  },
  shen_lvmeng: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["shelie", "gongxin"],
    groupInGuozhan: "wu",
  },
  dianwei: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["qiangxi"],
  },
  xunyu: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["quhu", "jieming"],
    clans: ["颍川荀氏"],
  },
  taishici: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["tianyi"],
    names: "太史|慈",
  },
  pangde: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["mashu", "mengjin"],
  },
  yanwen: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["shuangxiong"],
    names: "颜|良-文|丑",
  },
  yuanshao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["luanji", "xueyi"],
    isZhugong: true,
  },
  pangtong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["lianhuan", "niepan"],
  },
  sp_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["bazhen", "huoji", "kanpo"],
    names: "诸葛|亮",
  },
  shen_zhugeliang: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["qixing", "kuangfeng", "dawu"],
    groupInGuozhan: "shu",
    names: "诸葛|亮",
  },
  shen_zhouyu: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["qinyin", "yeyan"],
    groupInGuozhan: "wu",
  },
  lusu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["haoshi", "dimeng"],
  },
  sunjian: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["yinghun"],
  },
  dongzhuo: {
    sex: "male",
    group: "qun",
    hp: 8,
    skills: ["jiuchi", "roulin", "benghuai", "baonue"],
    isZhugong: true,
  },
  jiaxu: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["wansha", "luanwu", "weimu"],
  },
  menghuo: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["huoshou", "zaiqi"],
  },
  zhurong: {
    sex: "female",
    group: "shu",
    hp: 4,
    skills: ["juxiang", "lieren"],
    names: "null|null",
  },
  caopi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["xingshang", "fangzhu", "songwei"],
    isZhugong: true,
  },
  xuhuang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["duanliang"],
  },
  shen_lvbu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["kuangbao", "wumou", "wuqian", "shenfen"],
    groupInGuozhan: "qun",
  },
  shen_caocao: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["guixin", "feiying"],
    groupInGuozhan: "wei",
  },

  jiangwei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["tiaoxin", "zhiji"],
  },

  // dengai: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["tuntian", "zaoxian"],
  // },
  // zhanghe: {
  //   sex: "male",
  //   group: "wei",
  //   hp: 4,
  //   skills: ["qiaobian"],
  // },
  // liushan: {
  //   sex: "male",
  //   group: "shu",
  //   hp: 3,
  //   skills: ["xiangle", "fangquan", "ruoyu"],
  //   isZhugong: true,
  // },
  // sunce: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 4,
  //   skills: ["jiang", "hunzi", "zhiba"],
  //   isZhugong: true,
  // },
  // zhangzhang: {
  //   sex: "male",
  //   group: "wu",
  //   hp: 3,
  //   skills: ["zhijian", "guzheng"],
  //   names: "张|昭-张|纮",
  // },
  // zuoci: {
  //   sex: "male",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["huashen", "xinsheng"],
  // },
  // caiwenji: {
  //   sex: "female",
  //   group: "qun",
  //   hp: 3,
  //   skills: ["beige", "duanchang"],
  // },
  // shen_simayi: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 4,
  //   skills: ["renjie", "sbaiyin", "lianpo"],
  //   groupInGuozhan: "wei",
  //   names: "司马|懿",
  // },
  // shen_zhaoyun: {
  //   sex: "male",
  //   group: "shen",
  //   hp: 2,
  //   skills: ["xinjuejing", "relonghun"],
  //   groupInGuozhan: "shu",
  // },
}

export default characters
