const characters = {
  caoren: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jushou"],
  },
  xiahouyuan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["shensu"],
    names: "夏侯|渊",
  },
  huangzhong: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["liegong"],
  },
  weiyan: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["kuanggu"],
  },
  xiaoqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["tianxiang", "hongyan"],
    names: "桥|null",
  },
  zhoutai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["buqu"],
  },
  zhangjiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["leiji", "guidao", "huangtian"],
    isZhugong: true,
  },
  yuji: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["guhuo"],
  },
  dianwei: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["qiangxi"],
  },
  xunyu: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["quhu", "jieming"],
    clans: ["颍川荀氏"],
  },
  sp_zhugeliang: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["bazhen", "huoji", "kanpo"],
    names: "诸葛|亮",
  },
  pangtong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["lianhuan", "niepan"],
  },
  taishici: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["tianyi"],
    names: "太史|慈",
  },

  pangde: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["mashu", "mengjin"],
  },
  yuanshao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["luanji", "xueyi"],
    isZhugong: true,
  },
  yanwen: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["shuangxiong"],
    names: "颜|良-文|丑",
  },
  caopi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["xingshang", "fangzhu", "songwei"],
    isZhugong: true,
  },
  xuhuang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["duanliang"],
  },
  zhurong: {
    sex: "female",
    group: "shu",
    hp: 4,
    skills: ["juxiang", "lieren"],
    names: "null|null",
  },
  menghuo: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["huoshou", "zaiqi"],
  },
  lusu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["haoshi", "dimeng"],
  },
  sunjian: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["yinghun"],
  },
  dongzhuo: {
    sex: "male",
    group: "qun",
    hp: 8,
    skills: ["jiuchi", "roulin", "benghuai", "baonue"],
    isZhugong: true,
  },
  jiaxu: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["luanwu", "wansha", "weimu"],
  },
  dengai: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["tuntian", "zaoxian"],
  },
  zhanghe: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["qiaobian"],
  },
  jiangwei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["tiaoxin", "zhiji"],
  },
  liushan: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["xiangle", "fangquan", "ruoyu"],
    isZhugong: true,
  },
  sunce: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["jiang", "hunzi", "zhiba"],
    isZhugong: true,
  },
  zhangzhang: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["zhijian", "guzheng"],
    names: "张|昭-张|纮",
  },
  zuoci: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["huashen", "xinsheng"],
  },
  caiwenji: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["beige", "duanchang"],
  },
  shen_guanyu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["wushen", "new_wuhun"],
    groupInGuozhan: "shu",
  },
  shen_lvmeng: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["shelie", "gongxin"],
    groupInGuozhan: "wu",
  },
  shen_zhouyu: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["yeyan", "qinyin"],
    groupInGuozhan: "wu",
  },
  shen_zhugeliang: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["qixing", "kuangfeng", "dawu"],
    groupInGuozhan: "shu",
    names: "诸葛|亮",
  },
  shen_lvbu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["baonu", "wumou", "ol_wuqian", "ol_shenfen"],
    groupInGuozhan: "qun",
  },
  shen_caocao: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["new_guixin", "feiying"],
    groupInGuozhan: "wei",
  },
  shen_simayi: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["renjie", "sbaiyin", "lianpo"],
    groupInGuozhan: "wei",
    names: "司马|懿",
  },
  shen_zhaoyun: {
    sex: "male",
    group: "shen",
    hp: 2,
    skills: ["xinjuejing", "relonghun"],
    groupInGuozhan: "shu",
  },
}

export default characters
