const characters = {
  huangzhong: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["liegong"],
  },
  weiyan: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["kuanggu"],
  },
  xiahouyuan: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["shensu"],
  },
  caoren: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["jushou"],
  },
  xiaoqiao: {
    sex: "female",
    group: "wu",
    hp: 3,
    skills: ["tianxiang", "hongyan"],
  },
  zhoutai: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["buqu"],
  },
  zhangjiao: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["leiji", "guidao", "huangtian"],
    isZhugong: true,
  },
  yuji: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["guhuo"],
  },
  dianwei: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["qiangxi"],
  },
  xunyu: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["quhu", "jieming"],
  },
  pangtong: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["lianhuan", "niepan"],
  },
  wolongzhuge: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["huoji", "bazhen", "kanpo"],
  },
  taishici: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["tianyi"],
  },
  pangde: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["mengjin", "mashu"],
  },
  yanliangwenchou: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["shuangxiong"],
  },
  yuanshao: {
    sex: "male",
    group: "qun",
    hp: 4,
    skills: ["luanji", "xueyi"],
    isZhugong: true,
  },
  xuhuang: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["duanliang"],
  },
  caopi: {
    sex: "male",
    group: "wei",
    hp: 3,
    skills: ["xingshang", "fangzhu", "songwei"],
    isZhugong: true,
  },
  sunjian: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["yinghun"],
  },
  dongzhuo: {
    sex: "male",
    group: "qun",
    hp: 8,
    skills: ["jiuchi", "roulin", "benghuai", "baonue"],
    isZhugong: true,
  },
  zhurong: {
    sex: "female",
    group: "shu",
    hp: 4,
    skills: ["juxiang", "lieren"],
  },
  menghuo: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["huoshou", "zaiqi"],
  },
  jiaxu: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["wansha", "weimu", "luanwu"],
  },
  lusu: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["haoshi", "dimeng"],
  },
  zhanghe: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["qiaobian"],
  },
  dengai: {
    sex: "male",
    group: "wei",
    hp: 4,
    skills: ["tuntian", "zaoxian"],
  },
  jiangwei: {
    sex: "male",
    group: "shu",
    hp: 4,
    skills: ["tiaoxin", "zhiji"],
  },
  liushan: {
    sex: "male",
    group: "shu",
    hp: 3,
    skills: ["xiangle", "fangquan", "ruoyu"],
    isZhugong: true,
  },
  sunce: {
    sex: "male",
    group: "wu",
    hp: 4,
    skills: ["jiang", "hunzi", "zhiba"],
    isZhugong: true,
  },
  zhangzhaozhanghong: {
    sex: "male",
    group: "wu",
    hp: 3,
    skills: ["zhijian", "guzheng"],
  },
  zuoci: {
    sex: "male",
    group: "qun",
    hp: 3,
    skills: ["xinsheng", "huashen"],
  },
  caiwenji: {
    sex: "female",
    group: "qun",
    hp: 3,
    skills: ["beige", "duanchang"],
  },
  le_guanyu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["wushen", "wuhun"],
    groupInGuozhan: "shu",
  },
  le_lvmeng: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["shelie", "gongxin"],
    groupInGuozhan: "wu",
  },
  le_zhouyu: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["qinyin", "yeyan"],
    groupInGuozhan: "wu",
  },
  le_zhugeliang: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["qixing", "kuangfeng", "dawu"],
    groupInGuozhan: "shu",
  },
  le_caocao: {
    sex: "male",
    group: "shen",
    hp: 3,
    skills: ["guixin", "feiying"],
    groupInGuozhan: "wei",
  },
  le_lvbu: {
    sex: "male",
    group: "shen",
    hp: 5,
    skills: ["kuangbao", "wumou", "wuqian", "shenfen"],
    groupInGuozhan: "qun",
  },
  le_zhaoyun: {
    sex: "male",
    group: "shen",
    hp: 2,
    skills: ["juejing", "longhun"],
    groupInGuozhan: "shu",
  },
  le_simayi: {
    sex: "male",
    group: "shen",
    hp: 4,
    skills: ["renjie", "sbaiyin", "lianpo"],
    groupInGuozhan: "wei",
  },
}

export default characters
