export default {
  "#guhuo1": "你信吗？",
  "#guhuo2": "猜猜看哪~",
  "#yuji:die": "竟然……被猜到了……",

  "#leiji1": "以我之真气，合天地之造化。",
  "#leiji2": "雷公助我！",
  "#guidao1": "天下大事，为我所控。",
  "#guidao2": "哼哼哼!",
  "#huangtian1": "苍天已死，黄天当立！",
  "#huangtian2": "岁在甲子，天下大吉！",
  "#zhangjiao:die": "黄天，也死了……",

  "#kuanggu1": "我会怕你吗？",
  "#kuanggu2": "真是美味啊！",
  "#weiyan:die": "谁敢杀我？",

  "#liegong1": "百步穿杨！",
  "#liegong2": "中！",
  "#huangzhong:die": "不得不服老啊！",

  "#jushou1": "尽管来吧！",
  "#jushou2": "我先休息一会！",
  "#caoren:die": "实在是守不住了。",

  "#shensu1": "取汝首级，犹如探囊取物。",
  "#shensu2": "吾善于千里袭人。",
  "#xiahouyuan:die": "竟然，比我还，快。",

  "#buqu1": "还不够！",
  "#buqu2": "我绝不会倒下！",
  "#zhoutai:die": "已经尽力了……",

  "#tianxiang1": "接着哦！",
  "#tianxiang2": "替我挡着！",
  "#hongyan": "（琴声）",
  "#xiaoqiao:die": "公瑾……我先走一步。",

  "#wushen1": "取汝狗头，犹如探囊取物。",
  "#wushen2": "还不速速领死！",
  "#wuhun1": "拿命来！",
  "#wuhun2": "谁来与我同去？！",
  "#shen_guanyu:die": "大仇得报，可以离开了……",

  "#shelie1": "略懂，略懂。",
  "#shelie2": "什么都略懂一点，生活更多彩一些。",
  "#gongxin1": "我替施主把把脉。",
  "#gongxin2": "攻城为下，攻心为上。",
  "#shen_lvmeng:die": "劫数难逃，我们别无选择……",

  "#qiangxi1": "看我三步之内取你小命！",
  "#qiangxi2": "吃我一戟！",
  "#dianwei:die": "主公，快走！",

  "#quhu1": "此乃驱虎吞狼之计。",
  "#quhu2": "借你之手，与他一搏吧。",
  "#jieming1": "我，永不背弃。",
  "#jieming2": "秉忠贞之志，守谦退之节。",
  "#xunyu:die": "主公要臣死，臣不得不死。",

  "#tianyi1": "我当要替天行道！",
  "#tianyi2": "请助我一臂之力！",
  "#taishici:die": "大丈夫，当带三尺之剑，立不世之功……",

  "#mengjin1": "我要杀你们个片甲不留！",
  "#mengjin2": "你可敢挡我？",
  "#pangde:die": "四面都是水，我命休矣……",

  "#shuangxiong1": "吾乃河北上将颜良文丑是也。",
  "#shuangxiong2": "快来与我等决一死战!",
  "#yanwen:die": "这红脸长须大将是……",

  "#luanji1": "弓箭手，准备放箭！",
  "#luanji2": "全都去死吧！",
  "#xueyi1": "崇王攘夷，生长尊贵。",
  "#xueyi2": "衣冠华胄，宜蒙优免。",
  "#yuanshao:die": "老天不助我袁家啊……",

  "#lianhuan1": "伤一敌可连其百！",
  "#lianhuan2": "通通连起来吧！",
  "#niepan1": "凤雏岂能消亡？",
  "#niepan2": "浴火重生！",
  "#pangtong:die": "看来我命中注定将丧命于此……",

  "#bazhen1": "你可识得此阵？",
  "#bazhen2": "太极生两仪，两仪生四象，四象生八卦。",
  "#huoji1": "燃烧吧！",
  "#huoji2": "此火可助我军大获全胜。",
  "#kanpo1": "雕虫小技！",
  "#kanpo2": "你的计谋被识破了！",
  "#sp_zhugeliang:die": "我的计谋竟被……",

  "#qixing1": "祈星辰之力，佑我蜀汉！",
  "#qixing2": "伏望天恩，誓讨汉贼！",
  "#kuangfeng1": "风~~起~~",
  "#kuangfeng2": "万事俱备，只欠业火。",
  "#dawu1": "此计可保你一时平安。",
  "#dawu2": "此非万全之策，唯惧天雷。",
  "#shen_zhugeliang:die": "今当远离，临表涕零，不知所言……",

  "#qinyin1": "（舒缓的琴声）",
  "#qinyin2": "（急促的琴声、燃烧声）",
  "#yeyan1": "（燃烧声）让这熊熊业火，焚尽你的罪恶！",
  "#yeyan2": "（燃烧声）聆听吧，这献给你的镇魂曲！",
  "#shen_zhouyu:die": "逝者不死，浴火重生。",

  "#haoshi1": "来来来，见面分一半。",
  "#haoshi2": "拿去拿去，莫跟哥哥客气！",
  "#dimeng1": "合纵连横，方能以弱胜强。",
  "#dimeng2": "以和为贵，以和为贵。",
  "#lusu:die": "此联盟已破，吴蜀休矣……",

  "#yinghun1": "不诛此贼三族，则吾死不瞑目！",
  "#yinghun2": "以吾魂魄，保佑吾儿之基业。",
  "#sunjian:die": "有埋伏，啊……",

  "#jiuchi1": "再来……一壶……",
  "#jiuchi2": "好酒！好酒！",
  "#roulin1": "美人儿，来，香一个~~",
  "#roulin2": "食色，性也~~",
  "#benghuai1": "我是不是该减肥了？",
  "#benghuai2": "呃……",
  "#baonue1": "顺我者昌，逆我者亡！",
  "#baonue2": "哈哈哈哈……",
  "#dongzhuo:die": "汉室衰落，非我一人之罪。",

  "#wansha1": "我要你三更死，谁敢留你到五更？",
  "#wansha2": "神仙难救，神仙难救啊……",
  "#luanwu1": "哭喊吧，哀求吧，挣扎吧，然后，死吧！",
  "#luanwu2": "哼哼哼……坐山观虎斗！",
  "#weimu1": "你奈我何？",
  "#weimu2": "此计伤不到我。",
  "#jiaxu:die": "我的时辰……也到了……",

  "#huoshou1": "通通算我的。",
  "#huoshou2": "背黑锅我来，送死？你去！",
  "#zaiqi1": "起——",
  "#zaiqi2": "丞相助我！",
  "#menghuo:die": "七纵之恩……来世……再报了……",

  "#juxiang1": "大王，看我的。",
  "#juxiang2": "小小把戏。",
  "#lieren1": "亮兵器吧。",
  "#lieren2": "尝尝我飞刀的厉害！",
  "#zhurong:die": "大王，我……先走一步了……",

  "#xingshang1": "来，管杀还管埋。",
  "#xingshang2": "我的是我的，你的还是我的。",
  "#fangzhu1": "给我翻过来。",
  "#fangzhu2": "死罪可免，活罪难赦。",
  "#songwei1": "仙福永享，寿与天齐！",
  "#songwei2": "千秋万载，一统江山！",
  "#caopi:die": "子建，子建……",

  "#duanliang1": "人是铁，饭是钢。",
  "#duanliang2": "截其源，断其粮，贼可擒也。",
  "#xuhuang:die": "一顿不吃饿得慌。",

  "#tiaoxin1": "汝等小儿，可敢杀我？",
  "#tiaoxin2": "贼将早降，可免一死。",
  "#zhiji1": "先帝之志，丞相之托，不可忘也！",
  "#zhiji2": "丞相厚恩，维万死不能相报。",
  "#guanxing_jiangwei1": "克复中原，指日可待！",
  "#guanxing_jiangwei2": "继丞相之遗志，讨篡汉之逆贼！",
  "#jiangwei:die": "我计不成，乃天命也……",
}
