const characters = {
	re_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_rejianxiong", "hujia"],
		isZhugong: true,
	},
	re_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["refankui", "reguicai"],
		names: "司马|懿",
	},
	re_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["reganglie", "new_qingjian"],
		names: "夏侯|惇",
	},
	re_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_retuxi"],
	},
	re_xuzhu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_reluoyi"],
	},
	re_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "new_reyiji"],
	},
	re_zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["luoshen", "qingguo"],
	},
	caozhang: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["rejiangchi"],
	},
	re_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rerende", "jijiang"],
		isZhugong: true,
	},
	re_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["new_rewusheng", "new_yijue"],
	},
	re_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["new_repaoxiao", "new_tishen"],
	},
	re_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["reguanxing", "kongcheng"],
		names: "诸葛|亮",
	},
	re_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["longdan", "new_yajiao"],
	},
	xf_yiji: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["xinfu_jijie", "xinfu_jiyuan"],
	},
	re_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["rezhiheng", "rejiuyuan"],
		isZhugong: true,
	},
};

export default characters;
