const characters = {
	re_caocao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_rejianxiong", "rehujia"],
		isZhugong: true,
	},
	re_simayi: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["refankui", "reguicai"],
	},
	re_xiahoudun: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["reganglie", "new_qingjian"],
	},
	re_zhangliao: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_retuxi"],
	},
	re_xuzhu: {
		sex: "male",
		group: "wei",
		hp: 4,
		skills: ["new_reluoyi"],
	},
	re_guojia: {
		sex: "male",
		group: "wei",
		hp: 3,
		skills: ["tiandu", "new_reyiji"],
	},
	re_zhenji: {
		sex: "female",
		group: "wei",
		hp: 3,
		skills: ["reluoshen", "qingguo"],
	},
	re_liubei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["rerende", "rejijiang"],
		isZhugong: true,
	},
	re_guanyu: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["new_rewusheng", "new_yijue"],
	},
	re_zhangfei: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["olpaoxiao", "oltishen"],
	},
	re_zhugeliang: {
		sex: "male",
		group: "shu",
		hp: 3,
		skills: ["reguanxing", "kongcheng"],
	},
	re_zhaoyun: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["ollongdan", "olyajiao"],
	},
	re_machao: {
		sex: "male",
		group: "shu",
		hp: 4,
		skills: ["mashu", "retieji"],
	},
	re_huangyueying: {
		sex: "female",
		group: "shu",
		hp: 3,
		skills: ["rejizhi", "reqicai"],
	},
	re_sunquan: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["rezhiheng", "rejiuyuan"],
		isZhugong: true,
	},
	re_ganning: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["qixi", "fenwei"],
	},
	re_lvmeng: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["keji", "qinxue", "rebotu"],
	},
	re_huanggai: {
		sex: "male",
		group: "wu",
		hp: 4,
		skills: ["rekurou", "zhaxiang"],
	},
	re_zhouyu: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["reyingzi", "refanjian"],
	},
	re_daqiao: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["reguose", "liuli"],
	},
	re_luxun: {
		sex: "male",
		group: "wu",
		hp: 3,
		skills: ["reqianxun", "relianying"],
	},
	re_sunshangxiang: {
		sex: "female",
		group: "wu",
		hp: 3,
		skills: ["xiaoji", "rejieyin"],
	},
	re_huatuo: {
		sex: "male",
		group: "qun",
		hp: 3,
		skills: ["jijiu", "new_reqingnang"],
	},
	re_lvbu: {
		sex: "male",
		group: "qun",
		hp: 5,
		skills: ["wushuang", "new_liyu"],
	},
	re_diaochan: {
		sex: "female",
		group: "qun",
		hp: 3,
		skills: ["lijian", "rebiyue"],
	},
};

export default characters;
