const translates = {
	re_caocao: "曹操",
	re_simayi: "司马懿",
	re_xiahoudun: "夏侯惇",
	re_zhangliao: "张辽",
	re_xuzhu: "许褚",
	re_guojia: "郭嘉",
	re_zhenji: "甄姬",
	re_liubei: "刘备",
	re_guanyu: "关羽",
	re_zhangfei: "张飞",
	re_zhugeliang: "诸葛亮",
	re_zhaoyun: "赵云",
	re_machao: "马超",
	re_huangyueying: "黄月英",
	re_sunquan: "孙权",
	re_ganning: "甘宁",
	re_lvmeng: "吕蒙",
	re_huanggai: "黄盖",
	re_zhouyu: "周瑜",
	re_daqiao: "大乔",
	re_luxun: "陆逊",
	re_sunshangxiang: "孙尚香",
	re_huatuo: "华佗",
	re_lvbu: "吕布",
	re_diaochan: "貂蝉",
};

export default translates;
